INSERT INTO Religions 
			(Type,								Description,								Civilopedia,								  	IconAtlas,	 					PortraitIndex, 	IconString)						   
VALUES	  
			('RELIGION_CBRX_MENNONISM',			'TXT_KEY_RELIGION_CBRX_MENNONISM',			'TXT_KEY_RELIGION_CBRX_MENNONISM_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	1,				'[ICON_RELIGION_CBRX_MENNONISM]'),
			('RELIGION_CBRX_BEKTASHISM',		'TXT_KEY_RELIGION_CBRX_BEKTASHISM',	        'TXT_KEY_RELIGION_CBRX_BEKTASHISM_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	2,				'[ICON_RELIGION_CBRX_BEKTASHISM]'),
			('RELIGION_CBRX_WAAQISM',		  	'TXT_KEY_RELIGION_CBRX_WAAQISM',			'TXT_KEY_RELIGION_CBRX_WAAQISM_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	3,				'[ICON_RELIGION_CBRX_WAAQISM]'),
			('RELIGION_CBRX_BON',			  	'TXT_KEY_RELIGION_CBRX_BON',		       	'TXT_KEY_RELIGION_CBRX_BON_PEDIA',				'CBRX_RELIGIONS_MASTER_ATLAS',	4,		   		'[ICON_RELIGION_CBRX_BON]'),
			('RELIGION_CBRX_SERGIANISM',		'TXT_KEY_RELIGION_CBRX_SERGIANISM',		    'TXT_KEY_RELIGION_CBRX_SERGIANISM_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	5,				'[ICON_RELIGION_CBRX_SERGIANISM]'),
			('RELIGION_CBRX_BAI_SHANGDI_HUI',	'TXT_KEY_RELIGION_CBRX_BAI_SHANGDI_HUI',	'TXT_KEY_RELIGION_CBRX_BAI_SHANGDI_HUI_PEDIA',	'CBRX_RELIGIONS_MASTER_ATLAS',	6,				'[ICON_RELIGION_CBRX_BAI_SHANGDI_HUI]'),
			('RELIGION_CBRX_SHAFII',			'TXT_KEY_RELIGION_CBRX_SHAFII',		     	'TXT_KEY_RELIGION_CBRX_SHAFII_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	7,				'[ICON_RELIGION_CBRX_SHAFII]'),
			('RELIGION_CBRX_KEJAWEN',			'TXT_KEY_RELIGION_CBRX_KEJAWEN',		    'TXT_KEY_RELIGION_CBRX_KEJAWEN_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	8,				'[ICON_RELIGION_CBRX_KEJAWEN]'),
			('RELIGION_CBRX_DARAMOOLEN',		'TXT_KEY_RELIGION_CBRX_DARAMOOLEN',		    'TXT_KEY_RELIGION_CBRX_DARAMOOLEN_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	9,				'[ICON_RELIGION_CBRX_DARAMOOLEN]'),
			('RELIGION_CBRX_INKOZE',			'TXT_KEY_RELIGION_CBRX_INKOZE',		     	'TXT_KEY_RELIGION_CBRX_INKOZE_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	10,				'[ICON_RELIGION_CBRX_INKOZE]'),
			('RELIGION_CBRX_CHINIGCHINIX',		'TXT_KEY_RELIGION_CBRX_CHINIGCHINIX',		'TXT_KEY_RELIGION_CBRX_CHINIGCHINIX_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	11,				'[ICON_RELIGION_CBRX_CHINIGCHINIX]'),
			('RELIGION_CBRX_IN_KALTONAL',		'TXT_KEY_RELIGION_CBRX_IN_KALTONAL',		'TXT_KEY_RELIGION_CBRX_IN_KALTONAL_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	12,				'[ICON_RELIGION_CBRX_IN_KALTONAL]'),
			('RELIGION_CBRX_GAIHWIIO',			'TXT_KEY_RELIGION_CBRX_GAIHWIIO',		   	'TXT_KEY_RELIGION_CBRX_GAIHWIIO_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	13,				'[ICON_RELIGION_CBRX_GAIHWIIO]'),
			('RELIGION_CBRX_RASTAFARIANISM',	'TXT_KEY_RELIGION_CBRX_RASTAFARIANISM',		'TXT_KEY_RELIGION_CBRX_RASTAFARIANISM_PEDIA',	'CBRX_RELIGIONS_MASTER_ATLAS',	14,				'[ICON_RELIGION_CBRX_RASTAFARIANISM]'),
			('RELIGION_CBRX_WALDENSIANISM',		'TXT_KEY_RELIGION_CBRX_WALDENSIANISM',		'TXT_KEY_RELIGION_CBRX_WALDENSIANISM_PEDIA',	'CBRX_RELIGIONS_MASTER_ATLAS',	15,				'[ICON_RELIGION_CBRX_WALDENSIANISM]');
			

INSERT INTO IconTextureAtlases 
			(Atlas, 											IconSize, 		Filename,   						IconsPerRow,  	IconsPerColumn)
VALUES		('CBRX_RELIGIONS_MASTER_ATLAS', 					 256, 			'CBRXNewReligionsMaster256.dds',	5, 				3),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					 214, 			'CBRXNewReligionsMaster214.dds',	5, 				3),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					 128, 			'CBRXNewReligionsMaster128.dds',	5, 				3),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  80, 		 	'CBRXNewReligionsMaster80.dds',		5, 				3),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  64, 		 	'CBRXNewReligionsMaster64.dds',		5, 				3),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  48, 		 	'CBRXNewReligionsMaster48.dds',		5, 				3),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  32, 		 	'CBRXNewReligionsMaster32.dds',		5, 				3),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  24, 		 	'CBRXNewReligionsMaster24.dds',		5, 				3),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  16, 		 	'CBRXNewReligionsMaster16.dds',		5, 				3);

INSERT INTO IconFontTextures 
			(IconFontTexture, 									IconFontTextureFile)
VALUES		('ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER', 	'CBRXNewReligionsMasterFontIcons');

INSERT INTO IconFontMapping 
			(IconName, 									IconFontTexture,	 										IconMapping)
VALUES		('ICON_RELIGION_CBRX_MENNONISM',			'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			   1),
			('ICON_RELIGION_CBRX_BEKTASHISM',			'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			   2),
			('ICON_RELIGION_CBRX_WAAQISM',				'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			   3),
			('ICON_RELIGION_CBRX_BON',					'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			   4),
			('ICON_RELIGION_CBRX_SERGIANISM',			'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			   5),
			('ICON_RELIGION_CBRX_BAI_SHANGDI_HUI',		'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			   6),
			('ICON_RELIGION_CBRX_SHAFII',				'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			   7),
			('ICON_RELIGION_CBRX_KEJAWEN',				'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			   8),
			('ICON_RELIGION_CBRX_DARAMOOLEN',			'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			   9),
			('ICON_RELIGION_CBRX_INKOZE',				'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			  10),
			('ICON_RELIGION_CBRX_CHINIGCHINIX',			'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			  11),
			('ICON_RELIGION_CBRX_IN_KALTONAL',			'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			  12),
			('ICON_RELIGION_CBRX_GAIHWIIO',				'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			  13),
			('ICON_RELIGION_CBRX_RASTAFARIANISM',		'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			  14),
			('ICON_RELIGION_CBRX_WALDENSIANISM',		'ICON_FONT_TEXTURE_CBRX_NEW_RELIGIONS_MASTER',			  15);
			
			

CREATE TABLE HRIDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO HRIDRemapper (Type) SELECT Type FROM Religions ORDER BY ID;
UPDATE Religions SET ID =	( SELECT HRIDRemapper.id-1 FROM HRIDRemapper WHERE Religions.Type = HRIDRemapper.Type);
DROP TABLE HRIDRemapper;

INSERT INTO Language_en_US 
			(Tag, 										Text) 
VALUES		("TXT_KEY_RELIGION_CBRX_MENNONISM", 			"Mennonism"),
			("TXT_KEY_RELIGION_CBRX_MENNONISM_ADJ", 		"Mennonite"),
			("TXT_KEY_RELIGION_CBRX_MENNONISM_PEDIA", 		"Mennonism"),
			("TXT_KEY_RELIGION_CBRX_BEKTASHISM", 			"Bektashism"),
			("TXT_KEY_RELIGION_CBRX_BEKTASHISM_ADJ", 		"Bektashi"),
			("TXT_KEY_RELIGION_CBRX_BEKTASHISM_PEDIA", 		"Bektashism"),
			("TXT_KEY_RELIGION_CBRX_WAAQISM", 				"Waaqism"),
			("TXT_KEY_RELIGION_CBRX_WAAQISM_ADJ", 			"Waaq"),
			("TXT_KEY_RELIGION_CBRX_WAAQISM_PEDIA", 		"Waaqism"),
			("TXT_KEY_RELIGION_CBRX_BON", 					"Bon"),
			("TXT_KEY_RELIGION_CBRX_BON_ADJ", 				"Bonpos"),
			("TXT_KEY_RELIGION_CBRX_BON_PEDIA", 			"Bon"),
			("TXT_KEY_RELIGION_CBRX_SERGIANISM", 			"Sergianism"),
			("TXT_KEY_RELIGION_CBRX_SERGIANISM_ADJ", 		"Sergianist"),
			("TXT_KEY_RELIGION_CBRX_SERGIANISM_PEDIA", 		"Sergianism"),
			("TXT_KEY_RELIGION_CBRX_BAI_SHANGDI_HUI", 		"Bài Shàngdì Huì"),
			("TXT_KEY_RELIGION_CBRX_BAI_SHANGDI_HUI_ADJ",	"Bài Shàngdì Huì"),
			("TXT_KEY_RELIGION_CBRX_BAI_SHANGDI_HUI_PEDIA", "Bài Shàngdì Huì"),
			("TXT_KEY_RELIGION_CBRX_SHAFII", 				"Shafi'i"),
			("TXT_KEY_RELIGION_CBRX_SHAFII_ADJ", 			"Shafi'i"),
			("TXT_KEY_RELIGION_CBRX_SHAFII_PEDIA", 			"Shafi'i"),
			("TXT_KEY_RELIGION_CBRX_KEJAWEN", 				"Kejawèn"),
			("TXT_KEY_RELIGION_CBRX_KEJAWEN_ADJ", 			""),
			("TXT_KEY_RELIGION_CBRX_KEJAWEN_PEDIA", 		"Kejawèn"),
			("TXT_KEY_RELIGION_CBRX_DARAMOOLEN", 			"Daramoolen"),
			("TXT_KEY_RELIGION_CBRX_DARAMOOLEN_ADJ", 		""),
			("TXT_KEY_RELIGION_CBRX_DARAMOOLEN_PEDIA", 		"Daramoolen"),
			("TXT_KEY_RELIGION_CBRX_INKOZE", 				"Inkoze"),
			("TXT_KEY_RELIGION_CBRX_INKOZE_ADJ", 			""),
			("TXT_KEY_RELIGION_CBRX_INKOZE_PEDIA", 			"Inkoze"),
			("TXT_KEY_RELIGION_CBRX_CHINIGCHINIX", 			"Chinigchinix"),
			("TXT_KEY_RELIGION_CBRX_CHINIGCHINIX_ADJ", 		""),
			("TXT_KEY_RELIGION_CBRX_CHINIGCHINIX_PEDIA",	"Chinigchinix"),
			("TXT_KEY_RELIGION_CBRX_IN_KALTONAL", 			"In Kaltonal"),
			("TXT_KEY_RELIGION_CBRX_IN_KALTONAL_ADJ", 		"In Kaltonal"),
			("TXT_KEY_RELIGION_CBRX_IN_KALTONAL_PEDIA", 	"In Kaltonal"),
			("TXT_KEY_RELIGION_CBRX_GAIHWIIO", 				"Gaihwi:io"),
			("TXT_KEY_RELIGION_CBRX_GAIHWIIO_ADJ", 			"Gaihwi:io"),
			("TXT_KEY_RELIGION_CBRX_GAIHWIIO_PEDIA", 		"Gaihwi:io"),
			("TXT_KEY_RELIGION_CBRX_RASTAFARIANISM", 		"Rastafarianism"),
			("TXT_KEY_RELIGION_CBRX_RASTAFARIANISM_ADJ", 	"Rastafarian"),
			("TXT_KEY_RELIGION_CBRX_RASTAFARIANISM_PEDIA", 	"Rastafarianism"),
			("TXT_KEY_RELIGION_CBRX_WALDENSIANISM", 		"Waldensianism"),
			("TXT_KEY_RELIGION_CBRX_WALDENSIANISM_ADJ", 	"Waldensian"),
			("TXT_KEY_RELIGION_CBRX_WALDENSIANISM_PEDIA", 	"Waldensianism");