INSERT INTO Religions 
			(Type,							Description,							Civilopedia,								IconAtlas,	 					PortraitIndex, 	IconString)						   
VALUES	  
			('RELIGION_MENNONISM',			'TXT_KEY_RELIGION_MENNONISM',			'TXT_KEY_RELIGION_MENNONISM_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	0,				'[ICON_RELIGION_MENNONISM]'),
			('RELIGION_BEKTASHISM',			'TXT_KEY_RELIGION_BEKTASHISM',	        'TXT_KEY_RELIGION_BEKTASHISM_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	1,				'[ICON_RELIGION_BEKTASHISM]'),
			('RELIGION_WAAQEFFANNAA',		'TXT_KEY_RELIGION_WAAQEFFANNAA',		'TXT_KEY_RELIGION_WAAQEFFANNAA_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	3,				'[ICON_RELIGION_WAAQEFFANNAA]'),
			('RELIGION_BON',			  	'TXT_KEY_RELIGION_BON',		       		'TXT_KEY_RELIGION_BON_PEDIA',				'CBRX_RELIGIONS_MASTER_ATLAS',	2,		   		'[ICON_RELIGION_BON]'),
			('RELIGION_SERGIANISM',			'TXT_KEY_RELIGION_SERGIANISM',		    'TXT_KEY_RELIGION_SERGIANISM_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	4,				'[ICON_RELIGION_SERGIANISM]'),
			('RELIGION_BAI_SHANGDI_HUI',	'TXT_KEY_RELIGION_BAI_SHANGDI_HUI',		'TXT_KEY_RELIGION_BAI_SHANGDI_HUI_PEDIA',	'CBRX_RELIGIONS_MASTER_ATLAS',	13,				'[ICON_RELIGION_BAI_SHANGDI_HUI]'),
			('RELIGION_SHAFII',				'TXT_KEY_RELIGION_SHAFII',		     	'TXT_KEY_RELIGION_SHAFII_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	11,				'[ICON_RELIGION_SHAFII]'),
			('RELIGION_KEJAWEN',			'TXT_KEY_RELIGION_KEJAWEN',		    	'TXT_KEY_RELIGION_KEJAWEN_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	5,				'[ICON_RELIGION_KEJAWEN]'),
			('RELIGION_TAGAI',				'TXT_KEY_RELIGION_TAGAI',		    	'TXT_KEY_RELIGION_TAGAI_PEDIA',				'CBRX_RELIGIONS_MASTER_ATLAS',	14,				'[ICON_RELIGION_TAGAI]'),
			('RELIGION_INKOZE',				'TXT_KEY_RELIGION_INKOZE',		     	'TXT_KEY_RELIGION_INKOZE_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	6,				'[ICON_RELIGION_INKOZE]'),
			('RELIGION_CHINIGCHINIX',		'TXT_KEY_RELIGION_CHINIGCHINIX',		'TXT_KEY_RELIGION_CHINIGCHINIX_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	7,				'[ICON_RELIGION_CHINIGCHINIX]'),
			('RELIGION_IN_KALTONAL',		'TXT_KEY_RELIGION_IN_KALTONAL',			'TXT_KEY_RELIGION_IN_KALTONAL_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	8,				'[ICON_RELIGION_IN_KALTONAL]'),
			('RELIGION_GAIHWIIO',			'TXT_KEY_RELIGION_GAIHWIIO',		   	'TXT_KEY_RELIGION_GAIHWIIO_PEDIA',			'CBRX_RELIGIONS_MASTER_ATLAS',	9,				'[ICON_RELIGION_GAIHWIIO]'),
			('RELIGION_RASTAFARIANISM',		'TXT_KEY_RELIGION_RASTAFARIANISM',		'TXT_KEY_RELIGION_RASTAFARIANISM_PEDIA',	'CBRX_RELIGIONS_MASTER_ATLAS',	10,				'[ICON_RELIGION_RASTAFARIANISM]'),
			('RELIGION_WALDENSIANISM',		'TXT_KEY_RELIGION_WALDENSIANISM',		'TXT_KEY_RELIGION_WALDENSIANISM_PEDIA',		'CBRX_RELIGIONS_MASTER_ATLAS',	12,				'[ICON_RELIGION_WALDENSIANISM]');
			

INSERT INTO IconTextureAtlases 
			(Atlas, 											IconSize, 		Filename,   						IconsPerRow,  	IconsPerColumn)
VALUES		('CBRX_RELIGIONS_MASTER_ATLAS', 					 256, 			'CBRXNewReligionsMaster256.dds',	8, 				8),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					 214, 			'CBRXNewReligionsMaster214.dds',	8, 				8),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					 128, 			'CBRXNewReligionsMaster128.dds',	8, 				8),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  80, 		 	'CBRXNewReligionsMaster80.dds',		8, 				8),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  64, 		 	'CBRXNewReligionsMaster64.dds',		8, 				8),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  48, 		 	'CBRXNewReligionsMaster48.dds',		8, 				8),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  32, 		 	'CBRXNewReligionsMaster32.dds',		8, 				8),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  24, 		 	'CBRXNewReligionsMaster24.dds',		8, 				8),
			('CBRX_RELIGIONS_MASTER_ATLAS', 					  16, 		 	'CBRXNewReligionsMaster16.dds',		8, 				8);

INSERT INTO IconFontTextures 
			(IconFontTexture, 							IconFontTextureFile)
VALUES		('ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER', 	'CBRXNewReligionsMasterFontIcons');

INSERT INTO IconFontMapping 
			(IconName, 								IconFontTexture,	 									IconMapping)
VALUES		('ICON_RELIGION_MENNONISM',				'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   0),
			('ICON_RELIGION_BEKTASHISM',			'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   1),
			('ICON_RELIGION_WAAQEFFANNAA',			'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   3),
			('ICON_RELIGION_BON',					'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   2),
			('ICON_RELIGION_SERGIANISM',			'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   4),
			('ICON_RELIGION_BAI_SHANGDI_HUI',		'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   13),
			('ICON_RELIGION_SHAFII',				'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   11),
			('ICON_RELIGION_KEJAWEN',				'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   5),
			('ICON_RELIGION_TAGAI',					'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   14),
			('ICON_RELIGION_INKOZE',				'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			   6),
			('ICON_RELIGION_CHINIGCHINIX',			'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			  7),
			('ICON_RELIGION_IN_KALTONAL',			'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			  8),
			('ICON_RELIGION_GAIHWIIO',				'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			  9),
			('ICON_RELIGION_RASTAFARIANISM',		'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			  10),
			('ICON_RELIGION_WALDENSIANISM',			'ICON_FONT_TEXTURE_NEW_RELIGIONS_MASTER',			  12);
			
			

CREATE TABLE HRIDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO HRIDRemapper (Type) SELECT Type FROM Religions ORDER BY ID;
UPDATE Religions SET ID =	( SELECT HRIDRemapper.id-1 FROM HRIDRemapper WHERE Religions.Type = HRIDRemapper.Type);
DROP TABLE HRIDRemapper;

INSERT INTO Language_en_US 
			(Tag, 										Text) 
VALUES		("TXT_KEY_RELIGION_MENNONISM", 				"Mennonism"),
			("TXT_KEY_RELIGION_MENNONISM_ADJ", 			"Mennonite"),
			("TXT_KEY_RELIGION_MENNONISM_PEDIA", 		"Mennonism"),
			("TXT_KEY_RELIGION_BEKTASHISM", 			"Bektashism"),
			("TXT_KEY_RELIGION_BEKTASHISM_ADJ", 		"Bektashi"),
			("TXT_KEY_RELIGION_BEKTASHISM_PEDIA", 		"Bektashism"),
			("TXT_KEY_RELIGION_WAAQEFFANNAA", 			"Waaqeffannaa"),
			("TXT_KEY_RELIGION_WAAQEFFANNAA_ADJ", 		"Waaq"),
			("TXT_KEY_RELIGION_WAAQEFFANNAA_PEDIA", 	"Waaqeffannaa"),
			("TXT_KEY_RELIGION_BON", 					"Bon"),
			("TXT_KEY_RELIGION_BON_ADJ", 				"Bonpos"),
			("TXT_KEY_RELIGION_BON_PEDIA", 				"Bon"),
			("TXT_KEY_RELIGION_SERGIANISM", 			"Sergianism"),
			("TXT_KEY_RELIGION_SERGIANISM_ADJ", 		"Sergianist"),
			("TXT_KEY_RELIGION_SERGIANISM_PEDIA", 		"Sergianism"),
			("TXT_KEY_RELIGION_BAI_SHANGDI_HUI", 		"Bài Shàngdì Huì"),
			("TXT_KEY_RELIGION_BAI_SHANGDI_HUI_ADJ",	"Bài Shàngdì Huì"),
			("TXT_KEY_RELIGION_BAI_SHANGDI_HUI_PEDIA", 	"Bài Shàngdì Huì"),
			("TXT_KEY_RELIGION_SHAFII", 				"Shafi'i"),
			("TXT_KEY_RELIGION_SHAFII_ADJ", 			"Shafi'i"),
			("TXT_KEY_RELIGION_SHAFII_PEDIA", 			"Shafi'i"),
			("TXT_KEY_RELIGION_KEJAWEN", 				"Kejawèn"),
			("TXT_KEY_RELIGION_KEJAWEN_ADJ", 			"Javanese"),
			("TXT_KEY_RELIGION_KEJAWEN_PEDIA", 			"Kejawèn"),
			("TXT_KEY_RELIGION_TAGAI", 					"Tagai"),
			("TXT_KEY_RELIGION_TAGAI_ADJ", 				"Kulin"),
			("TXT_KEY_RELIGION_TAGAI_PEDIA", 			"Tagai"),
			("TXT_KEY_RELIGION_INKOZE", 				"Inkoze"),
			("TXT_KEY_RELIGION_INKOZE_ADJ", 			"Dene"),
			("TXT_KEY_RELIGION_INKOZE_PEDIA", 			"Inkoze"),
			("TXT_KEY_RELIGION_CHINIGCHINIX", 			"Chinigchinix"),
			("TXT_KEY_RELIGION_CHINIGCHINIX_ADJ", 		"Tongva"),
			("TXT_KEY_RELIGION_CHINIGCHINIX_PEDIA",		"Chinigchinix"),
			("TXT_KEY_RELIGION_IN_KALTONAL", 			"In Kaltonal"),
			("TXT_KEY_RELIGION_IN_KALTONAL_ADJ", 		"In Kaltonal"),
			("TXT_KEY_RELIGION_IN_KALTONAL_PEDIA", 		"In Kaltonal"),
			("TXT_KEY_RELIGION_GAIHWIIO", 				"Gaihwi:io"),
			("TXT_KEY_RELIGION_GAIHWIIO_ADJ", 			"Gaihwi:io"),
			("TXT_KEY_RELIGION_GAIHWIIO_PEDIA", 		"Gaihwi:io"),
			("TXT_KEY_RELIGION_RASTAFARIANISM", 		"Rastafarianism"),
			("TXT_KEY_RELIGION_RASTAFARIANISM_ADJ", 	"Rastafarian"),
			("TXT_KEY_RELIGION_RASTAFARIANISM_PEDIA", 	"Rastafarianism"),
			("TXT_KEY_RELIGION_WALDENSIANISM", 			"Waldensianism"),
			("TXT_KEY_RELIGION_WALDENSIANISM_ADJ", 		"Waldensian"),
			("TXT_KEY_RELIGION_WALDENSIANISM_PEDIA", 	"Waldensianism");