
	
INSERT INTO UnitPromotions
		(Type,									Description,									Help,												Sound,				CombatPercent,		IconAtlas,					PortraitIndex,			PediaType,			PediaEntry)
VALUES	('PROMOTION_SEPULCHRE_COMBAT_BONUS',	'TXT_KEY_PROMOTION_SEPULCHRE_COMBAT_BONUS',		'TXT_KEY_PROMOTION_SEPULCHRE_COMBAT_BONUS_HELP',	'AS2D_IF_LEVELUP',	15,					'MC_JERUSALEM_PROMO_ATLAS',	4,						'PEDIA_SHARED',		'TXT_KEY_PROMOTION_SEPULCHRE_COMBAT_BONUS'),
		('PROMOTION_UA_COMBAT_BONUS',			'TXT_KEY_PROMOTION_UA_COMBAT_BONUS',			'TXT_KEY_PROMOTION_UA_COMBAT_BONUS_HELP',			'AS2D_IF_LEVELUP',	15,					'ABILITY_ATLAS',			59,						'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_UA_COMBAT_BONUS');

INSERT INTO Features
		(Type,									Description,									Help,												Civilopedia,										ArtDefineTag,						Movement,		AddsFreshWater,		YieldNotAdditive,	WorldSoundscapeAudioScript,	EffectTypeTag,	PortraitIndex,	IconAtlas)
VALUES	('FEATURE_MC_JERUSALEM_LAZARUS_WATER',	'TXT_KEY_FEATURE_MC_JERUSALEM_LAZARUS_WATER',	'TXT_KEY_FEATURE_MC_JERUSALEM_LAZARUS_WATER_HELP',	'TXT_KEY_FEATURE_MC_JERUSALEM_LAZARUS_WATER_PEDIA',	'ART_DEF_FEATURE_FLOOD_PLAINS',		1,				1,					1,					'ASSS_AMBIENCE_JUNGLE',		'WATER',		17,				'BW_ATLAS_1');

INSERT INTO Policies
		(Type,							Description)
VALUES	('POLICY_MC_CRUCIFORM_SWORD',	'TXT_KEY_POLICY_MC_CRUCIFORM_SWORD');

--CREATE TABLE IF NOT EXISTS KnightlyOrders
--		(ID INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT UNIQUE NOT NULL, Dummy TEXT UNIQUE REFERENCES Buildings(Type) NOT NULL, Policy TEXT REFERENCES Policies(Type) DEFAULT NULL, Building TEXT REFERENCES Buildings(Type) NOT NULL, Unit TEXT REFERENCES Units(Type) NOT NULL, Promotion TEXT REFERENCES UnitPromotions(Type) NOT NULL, Head TEXT DEFAULT NULL, Head2 TEXT DEFAULT NULL, Body TEXT DEFAULT NULL, IconIndex INTEGER DEFAULT NULL, IconAtlas TEXT REFERENCES IconTextureAtlases(Atlas) DEFAULT NULL , Banner TEXT DEFAULT NULL);

--INSERT INTO KnightlyOrders
--		(Type,						Dummy,								Policy,							Building,											Unit,									Promotion,							Head,						Head2,					Body,							IconIndex,	IconAtlas,						Banner)
--VALUES	('ORDER_MC_HOSPITALLER',	'BUILDING_MC_JERUSALEM_ST_JOHN',	NULL,							'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'UNIT_MC_JERUSALEM_CRUSADER_ST_JOHN',	'PROMOTION_MC_JERUSALEM_ST_JOHN',	'Knights Hospitaller',		NULL,					'TXT_KEY_JERUSALEM_ST_JOHN',	3,			'MC_JERUSALEM_BANNERS_ATLAS',	'HospitallerBanner.dds'),
--		('ORDER_MC_LAZARUS',		'BUILDING_MC_JERUSALEM_LAZARUS',	NULL,							'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'UNIT_MC_JERUSALEM_CRUSADER_LAZARUS',	'PROMOTION_MC_JERUSALEM_LAZARUS',	'Order of Saint Lazarus',	NULL,					'TXT_KEY_JERUSALEM_LAZARUS',	2,			'MC_JERUSALEM_BANNERS_ATLAS',	'LazarusBanner.dds'),
--		('ORDER_MC_SEPULCHRE',		'BUILDING_MC_JERUSALEM_SEPULCHRE',	NULL,							'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'UNIT_MC_JERUSALEM_CRUSADER_SEPULCHRE',	'PROMOTION_MC_JERUSALEM_SEPULCHRE',	'Order of the',				'Holy Sepulchre',		'TXT_KEY_JERUSALEM_SEPULCHRE',	0,			'MC_JERUSALEM_BANNERS_ATLAS',	'SepulchreBanner.dds'),
--		('ORDER_MC_TEUTONIC',		'BUILDING_MC_JERUSALEM_TEUTONIC',	NULL,							'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',		'UNIT_MC_JERUSALEM_CRUSADER_TEUTONIC',	'PROMOTION_MC_JERUSALEM_TEUTONIC',	'Teutonic Order',			NULL,					'TXT_KEY_JERUSALEM_TEUTONIC',	1,			'MC_JERUSALEM_BANNERS_ATLAS',	'TeutonicBanner.dds'),
--		('ORDER_MC_TEMPLAR',		'BUILDING_MC_JERUSALEM_TEMPLARS',	NULL,							'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',		'UNIT_MC_JERUSALEM_CRUSADER_TEMPLARS',	'PROMOTION_MC_JERUSALEM_TEMPLARS',	'Knights Templar',			NULL,					'TXT_KEY_JERUSALEM_TEMPLARS',	4,			'MC_JERUSALEM_BANNERS_ATLAS',	'TemplarBanner.dds'),
--		('ORDER_MC_CRUCIFORM',		'BUILDING_MC_JERUSALEM_CRUCIFORM',	'POLICY_MC_CRUCIFORM_SWORD',	'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',		'UNIT_MC_JERUSALEM_CRUSADER_TEMPLARS',	'PROMOTION_MC_JERUSALEM_TEMPLARS',	'Brotherhood of',			'the Cruciform Sword',	'TXT_KEY_JERUSALEM_CRUCIFORM',	5,			'MC_JERUSALEM_BANNERS_ATLAS',	'CruciformBanner.dds');
