--==========================================================================================================================
-- IconTextureAtlases
--==========================================================================================================================
INSERT INTO IconTextureAtlases 
			(Atlas, 								IconSize, 	Filename, 										IconsPerRow, 	IconsPerColumn)
VALUES		('MC_JERUSALEM_BANNERS_ATLAS', 			256, 		'MC_JerusalemBannersAtlas_256.dds',				6, 				1),
			('MC_JERUSALEM_BANNERS_ATLAS', 			128, 		'MC_JerusalemBannersAtlas_128.dds',				6, 				1),
			('MC_JERUSALEM_BANNERS_ATLAS', 			80, 		'MC_JerusalemBannersAtlas_80.dds',				6, 				1),
			('MC_JERUSALEM_BANNERS_ATLAS', 			64, 		'MC_JerusalemBannersAtlas_64.dds',				6, 				1),
			('MC_JERUSALEM_BANNERS_ATLAS', 			45, 		'MC_JerusalemBannersAtlas_45.dds',				6, 				1);
--==========================================================================================================================
--==========================================================================================================================