---------------------------
--Civilizations
---------------------------

INSERT INTO Civilizations 
		(Type,													         Description,							            ShortDescription,									     Adjective,								                 CivilopediaTag,					                     DefaultPlayerColor,						       ArtDefineTag,						      ArtStyleType,			                        PortraitIndex,					    IconAtlas,								   AlphaIconAtlas,					                MapImage,			                       ArtStyleSuffix,		 ArtStylePrefix,	   DawnOfManQuote,				                                 DawnOfManImage,			             SoundtrackTag)
VALUES	('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH',		                 'TXT_KEY_MISSISSIPPI_MOD_TOMATEKH_DESC',			'TXT_KEY_MISSISSIPPI_MOD_TOMATEKH_SHORT_DESC',			 'TXT_KEY_MISSISSIPPI_MOD_TOMATEKH_ADJECTIVE',			 'TXT_KEY_CIVLOPEDIA_MISSISSIPPI_MOD_TOMATEKH',			 'PLAYERCOLOR_MISSISSIPPI_MOD_TOMATEKH',		   'ART_DEF_CIVILIZATION_IROQUOIS',			  'ARTSTYLE_SOUTH_AMERICA',                     0,									'MISSISSIPPI_MOD_TOMATEKH_ATLAS',		   'MISSISSIPPI_MOD_TOMATEKH_ALPHA_ATLAS',			'MississippiModMap.dds',			       '_AMER',			     'AMERICAN',		   'TXT_KEY_CIV5_DAWN_MISSISSIPPI_MOD_TOMATEKH_TEXT',			 'MississippiModDoM.dds',                   'Iroquois');

INSERT INTO Civilization_Leaders 
		(CivilizationType,											                                  LeaderheadType)
VALUES	('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH',				                   'LEADER_MISSISSIPPI_MOD_TOMATEKH');

INSERT INTO Civilization_FreeBuildingClasses 
		(CivilizationType,											                       BuildingClassType)
VALUES	('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH',				                      'BUILDINGCLASS_PALACE');

INSERT INTO Civilization_FreeTechs 
		(CivilizationType,																			  TechType)
VALUES	('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH',				                            'TECH_AGRICULTURE');

INSERT INTO Civilization_FreeUnits 
		(CivilizationType,							    UnitClassType,					Count,						     UnitAIType)
VALUES	('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH',	    'UNITCLASS_SETTLER',				1,						'UNITAI_SETTLE');

INSERT INTO Civilization_UnitClassOverrides 
		(CivilizationType,											                UnitClassType,						                                                UnitType)
VALUES	('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH',				                    'UNITCLASS_LONGSWORDSMAN',							         'UNIT_MISSISSIPPI_MOD_TOMATEKH');

INSERT INTO Civilization_BuildingClassOverrides 
		(CivilizationType,											               BuildingClassType,						                               BuildingType)
VALUES	('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH',				                   'BUILDINGCLASS_TEMPLE',							'BUILDING_MISSISSIPPI_MOD_TOMATEKH');

INSERT INTO Civilization_Religions 
		(CivilizationType,											                       ReligionType)
VALUES	('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH',				               'RELIGION_PROTESTANTISM');

INSERT INTO Colors 
		(Type,														 Red,		  Green,	   Blue,			Alpha)
VALUES	('COLOR_PLAYER_MISSISSIPPI_MOD_TOMATEKH_ICON',				 0.255,       0.341,       0.506,               1), --0.341
		('COLOR_PLAYER_MISSISSIPPI_MOD_TOMATEKH_BACKGROUND',	     0.988,       0.792,       0.506,               1);

INSERT INTO PlayerColors 
		(Type,							                    PrimaryColor,			                                    SecondaryColor,															TextColor)
VALUES	('PLAYERCOLOR_MISSISSIPPI_MOD_TOMATEKH',			'COLOR_PLAYER_MISSISSIPPI_MOD_TOMATEKH_ICON',				'COLOR_PLAYER_MISSISSIPPI_MOD_TOMATEKH_BACKGROUND',						'COLOR_PLAYER_WHITE_TEXT');

INSERT INTO Civilization_CityNames 
			(CivilizationType, 				                                                          CityName)
VALUES		('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_1'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_2'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_3'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_4'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_5'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 		    'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_6'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_7'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_8'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_9'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_10'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_11'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_12'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_13'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_14'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_15'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_16'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_17'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_18'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_19'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_20'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_21'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_22'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_23'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 		    'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_24'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_25'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 		    'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_26'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_27'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_28'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_29'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_30'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_31'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_32'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_33'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_34'),
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_CITY_NAME_MISSISSIPPI_MOD_TOMATEKH_35');

INSERT INTO Civilization_SpyNames 
			(CivilizationType, 				                                                          SpyName)
VALUES		('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_0'),	
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_1'),	
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_2'),	
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_3'),	
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_4'),	
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_5'),	
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_6'),	
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_7'),	
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_8'),	
			('CIVILIZATION_MISSISSIPPI_MOD_TOMATEKH', 			'TXT_KEY_SPY_NAME_MISSISSIPPI_MOD_TOMATEKH_9');

---------------------------
--Traits
---------------------------

INSERT INTO Traits 
		(Type,											                                     Description,						                                  ShortDescription)
VALUES	('TRAIT_MISSISSIPPI_MOD_TOMATEKH',				        'TXT_KEY_TRAIT_MISSISSIPPI_MOD_TOMATEKH',							'TXT_KEY_TRAIT_MISSISSIPPI_MOD_TOMATEKH_SHORT');

---------------------------
--Leaders
---------------------------

INSERT INTO Leaders 
		(Type,												  Description,													      Civilopedia,															  CivilopediaTag,									 ArtDefineTag,										VictoryCompetitiveness,		WonderCompetitiveness,		MinorCivCompetitiveness,	 Boldness,		DiploBalance,		WarmongerHate,		DenounceWillingness,		DoFWillingness,			Loyalty,		Neediness,		Forgiveness,	Chattiness,		Meanness,	PortraitIndex,	                               IconAtlas)
VALUES	('LEADER_MISSISSIPPI_MOD_TOMATEKH',			          'TXT_KEY_LEADER_MISSISSIPPI_MOD_TOMATEKH_DESC',				      'TXT_KEY_LEADER_MISSISSIPPI_MOD_TOMATEKH_PEDIA',					      'TXT_KEY_LEADER_MISSISSIPPI_MOD_TOMATEKH',		 'Mississippi_Mod_Tomatekh_Leader_Scene.xml',						     4,							3,							  6,            6,                 5,                   6,                        6,                     4,               6,                2,                2,             2,            5,               1,			'MISSISSIPPI_MOD_TOMATEKH_ATLAS');

INSERT INTO Leader_Traits 
		(LeaderType,											                              TraitType)
VALUES	('LEADER_MISSISSIPPI_MOD_TOMATEKH',				               'TRAIT_MISSISSIPPI_MOD_TOMATEKH');

INSERT INTO Leader_MajorCivApproachBiases 
			(LeaderType, 											MajorCivApproachType, 				 Bias)
VALUES		('LEADER_MISSISSIPPI_MOD_TOMATEKH', 			    'MAJOR_CIV_APPROACH_WAR', 					4),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		    'MAJOR_CIV_APPROACH_HOSTILE', 					5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 	      'MAJOR_CIV_APPROACH_DECEPTIVE', 					8),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		    'MAJOR_CIV_APPROACH_GUARDED', 					8),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		     'MAJOR_CIV_APPROACH_AFRAID', 					2),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 	       'MAJOR_CIV_APPROACH_FRIENDLY', 					4),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		    'MAJOR_CIV_APPROACH_NEUTRAL', 					6);

INSERT INTO Leader_MinorCivApproachBiases 
			(LeaderType, 											MinorCivApproachType, 				 Bias)
VALUES		('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		     'MINOR_CIV_APPROACH_IGNORE', 					4),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 	       'MINOR_CIV_APPROACH_FRIENDLY', 					6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 	     'MINOR_CIV_APPROACH_PROTECTIVE', 					6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 	       'MINOR_CIV_APPROACH_CONQUEST', 					4),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 	          'MINOR_CIV_APPROACH_BULLY', 					4);

INSERT INTO Leader_Flavors 
			(LeaderType, 													FlavorType, 					   Flavor)
VALUES		('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					  'FLAVOR_OFFENSE', 							6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					  'FLAVOR_DEFENSE', 							6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 				 'FLAVOR_CITY_DEFENSE', 							7),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 			'FLAVOR_MILITARY_TRAINING', 							7),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 						'FLAVOR_RECON', 							7),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					   'FLAVOR_RANGED', 							6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					   'FLAVOR_MOBILE', 							3),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 						'FLAVOR_NAVAL', 							3),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 			      'FLAVOR_NAVAL_RECON', 							3),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 			     'FLAVOR_NAVAL_GROWTH', 							3),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 	   'FLAVOR_NAVAL_TILE_IMPROVEMENT', 							3),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 						  'FLAVOR_AIR', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 				    'FLAVOR_EXPANSION', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					   'FLAVOR_GROWTH', 						    7),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 			 'FLAVOR_TILE_IMPROVEMENT', 							6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 			   'FLAVOR_INFRASTRUCTURE', 							6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 				   'FLAVOR_PRODUCTION', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 						 'FLAVOR_GOLD', 							6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					  'FLAVOR_SCIENCE', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					  'FLAVOR_CULTURE', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					'FLAVOR_HAPPINESS', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 				 'FLAVOR_GREAT_PEOPLE', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					   'FLAVOR_WONDER', 							6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					 'FLAVOR_RELIGION', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					'FLAVOR_DIPLOMACY', 							6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					'FLAVOR_SPACESHIP', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 			 'FLAVOR_WATER_CONNECTION', 							3),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 						 'FLAVOR_NUKE', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					 'FLAVOR_USE_NUKE', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					'FLAVOR_ESPIONAGE', 							7),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 				      'FLAVOR_ANTIAIR', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 				  'FLAVOR_AIR_CARRIER', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		          'FLAVOR_ARCHAEOLOGY', 							5),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		   'FLAVOR_I_LAND_TRADE_ROUTE', 							7),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		    'FLAVOR_I_SEA_TRADE_ROUTE', 							3),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		       'FLAVOR_I_TRADE_ORIGIN', 							7),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 		  'FLAVOR_I_TRADE_DESTINATION', 							6),
			('LEADER_MISSISSIPPI_MOD_TOMATEKH', 					  'FLAVOR_AIRLIFT', 							5);

---------------------------
--Diplomacy
---------------------------

INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_MISSISSIPPI_MOD_TOMATEKH',			'RESPONSE_FIRST_GREETING',			'TXT_KEY_LEADER_MISSISSIPPI_MOD_TOMATEKH_FIRST_GREETING_%',				'1');
INSERT INTO Diplomacy_Responses (LeaderType, ResponseType, Response, Bias) VALUES ('LEADER_MISSISSIPPI_MOD_TOMATEKH',			'RESPONSE_DEFEATED',				'TXT_KEY_LEADER_MISSISSIPPI_MOD_TOMATEKH_DEFEATED_%',					'1');