--==========================================================================================================================	
-- DIPLOMACY
--==========================================================================================================================	
-- Diplomacy_Responses
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Diplomacy_Responses
		(LeaderType, 			ResponseType, 									Response, 															Bias)
VALUES 	('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_ATTACKED_HOSTILE', 					'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_ATTACKED_GENERIC%', 					500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_DEFEATED', 							'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_DEFEATED%', 							500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_DOW_GENERIC', 						'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_DOW_GENERIC%', 							500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_EXPANSION_SERIOUS_WARNING', 			'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_EXPANSION_SERIOUS_WARNING%', 			500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_FIRST_GREETING', 						'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_FIRSTGREETING%', 						500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_GREETING_AT_WAR_HOSTILE', 			'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_GREETING_AT_WAR_HOSTILE%', 				500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_GREETING_POLITE_HELLO', 				'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_GREETING_POLITE_HELLO%', 				500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_GREETING_NEUTRAL_HELLO', 				'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_GREETING_NEUTRAL_HELLO%', 				500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_GREETING_HOSTILE_HELLO', 				'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_GREETING_HOSTILE_HELLO%', 				500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING', 'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_HOSTILE_AGGRESSIVE_MILITARY_WARNING%', 	500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_INFLUENTIAL_ON_AI', 					'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_INFLUENTIAL_ON_AI%', 					500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_INFLUENTIAL_ON_HUMAN', 				'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_INFLUENTIAL_ON_HUMAN%', 				500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_LETS_HEAR_IT', 						'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_LETS_HEAR_IT%', 						500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_LUXURY_TRADE', 						'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_LUXURY_TRADE%', 						500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_NO_PEACE', 							'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_NO_PEACE%', 							500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_OPEN_BORDERS_EXCHANGE', 				'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_OPEN_BORDERS_EXCHANGE%', 				500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_PEACE_MADE_BY_HUMAN_GRACIOUS', 		'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_LOSEWAR%', 								500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_REPEAT_NO', 							'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_REPEAT_NO%', 							500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_RESPONSE_REQUEST', 					'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_RESPONSE_REQUEST%', 					500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 		'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_RESPONSE_TO_BEING_DENOUNCED%', 			500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_TOO_SOON_NO_PEACE', 					'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_TOO_SOON_NO_PEACE_1%', 					500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_WINNER_PEACE_OFFER', 					'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_WINWAR%', 								500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_WORK_AGAINST_SOMEONE', 				'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_DENOUNCE%', 							500),
		('LEADER_SF_IBRAHIM_RUGOVA', 	'RESPONSE_WORK_WITH_US', 						'TXT_KEY_LEADER_SF_IBRAHIM_RUGOVA_DEC_FRIENDSHIP%', 						500);