INSERT OR REPLACE INTO CustomModOptions(Name, Value) VALUES('GLOBAL_GREATWORK_YIELDTYPES', 1);

UPDATE Buildings
  SET GreatWorkCount=1, GreatWorkSlotType='GREAT_WORK_SLOT_ART_ARTIFACT', GreatWorkYieldType='NO_YIELD'
  WHERE BuildingClass='BUILDINGCLASS_BANK';
