--==========================================================================================================================	
-- UNITS
--==========================================================================================================================	
--------------------------------------------------------------------------------------------------------------------------
-- UnitClasses
--------------------------------------------------------------------------------------------------------------------------	
INSERT OR REPLACE INTO UnitClasses 	
		(Type, 								Description, 							DefaultUnit)
VALUES	('UNITCLASS_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_UNIT_JFD_GREAT_PHILOSOPHER',   'UNIT_JFD_GREAT_PHILOSOPHER');
--------------------------------------------------------------------------------------------------------------------------	
-- UNITS
--------------------------------------------------------------------------------------------------------------------------
INSERT OR REPLACE INTO Units 	
		(Type, 							Class,								WorkRate,	DontShowYields, Cost, Moves, FaithCost, CivilianAttackPriority, Special, MoveAfterPurchase, Domain, DefaultUnitAI, Description, 							Strategy,										 Civilopedia, 								 UnitArtInfoEraVariation,	AdvancedStartCost,	CombatLimit, UnitArtInfo, 							UnitFlagIconOffset,	UnitFlagAtlas,								MoveRate, PortraitIndex, 	IconAtlas)
SELECT	'UNIT_JFD_GREAT_PHILOSOPHER',	'UNITCLASS_JFD_GREAT_PHILOSOPHER',  0,			DontShowYields, Cost, Moves, FaithCost, CivilianAttackPriority, Special, MoveAfterPurchase, Domain, DefaultUnitAI, 'TXT_KEY_UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_UNIT_JFD_GREAT_PHILOSOPHER_STRATEGY',	 'TXT_KEY_CIV5_JFD_GREAT_PHILOSOPHER_TEXT',  1,							AdvancedStartCost,  CombatLimit, 'ART_DEF_UNIT_JFD_GREAT_PHILOSOPHER',	0,					'JFD_GREAT_PHILOSOPHERS_UNIT_FLAG_ATLAS',	MoveRate, 0, 				'JFD_GREAT_PHILOSOPHERS_ICON_ATLAS'
FROM Units WHERE Type = 'UNIT_SCIENTIST';
--------------------------------------------------------------------------------------------------------------------------	
-- UnitGameplay2DScripts
--------------------------------------------------------------------------------------------------------------------------	
INSERT OR REPLACE INTO UnitGameplay2DScripts 	
		(UnitType, 						SelectionSound,	FirstSelectionSound)
SELECT	'UNIT_JFD_GREAT_PHILOSOPHER', 	SelectionSound,	FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_SCIENTIST';	
--------------------------------------------------------------------------------------------------------------------------		
-- Unit_AITypes
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_AITypes 	
		(UnitType, 						UnitAIType)
SELECT	'UNIT_JFD_GREAT_PHILOSOPHER',	UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_SCIENTIST';	
--------------------------------------------------------------------------------------------------------------------------	
-- Unit_Flavors
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_Flavors 	
		(UnitType, 						FlavorType,	 Flavor)
SELECT	'UNIT_JFD_GREAT_PHILOSOPHER', 	FlavorType,	 Flavor
FROM Unit_Flavors WHERE UnitType = 'UNIT_SCIENTIST';
--------------------------------------------------------------------------------------------------------------------------
-- Unit_UniqueNames
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Unit_UniqueNames 	
		(UnitType, 						UniqueName,										  EraType)
VALUES	('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_01',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_02',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_03',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_04',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_05',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_06',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_07',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_08',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_09',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_10',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_11',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_12',  'ERA_ANCIENT'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_13',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_14',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_15',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_16',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_17',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_18',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_19',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_20',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_21',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_22',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_23',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_24',  'ERA_CLASSICAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_25',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_26',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_27',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_28',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_29',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_30',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_31',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_32',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_33',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_34',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_35',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_36',  'ERA_MEDIEVAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_37',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_38',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_39',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_40',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_41',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_42',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_43',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_44',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_45',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_46',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_47',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_48',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_49',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_50',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_51',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_52',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_53',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_54',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_55',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_56',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_57',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_58',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_59',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_60',  'ERA_RENAISSANCE'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_61',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_62',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_63',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_64',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_65',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_66',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_67',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_68',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_69',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_70',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_71',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_72',  'ERA_INDUSTRIAL'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_73',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_74',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_75',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_76',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_77',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_78',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_79',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_80',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_81',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_82',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_83',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_84',  'ERA_MODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_85',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_86',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_87',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_88',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_89',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_90',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_91',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_92',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_93',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_94',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_95',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_96',  'ERA_POSTMODERN'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_97',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_98',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_99',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_100',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_101',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_102',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_103',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_104',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_105',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_106',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_107',  'ERA_INFORMATION'),
		('UNIT_JFD_GREAT_PHILOSOPHER',	'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_108',  'ERA_INFORMATION');

UPDATE Unit_UniqueNames
SET EraType = 'ERA_ENLIGHTENMENT'
WHERE EraType = 'ERA_RENAISSANCE' AND UniqueName IN ('TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_49', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_50', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_51', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_52', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_53', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_54', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_55', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_56', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_57', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_58', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_59', 'TXT_KEY_GREAT_PERSON_JFD_GREAT_PHILOSOPHER_60')
AND EXISTS (SELECT Type FROM Eras WHERE Type = 'ERA_ENLIGHTENMENT');
--==========================================================================================================================
--==========================================================================================================================