--==========================================================================================================================		
-- POLICIES
--==========================================================================================================================
--------------------------------------------------------------------------------------------------------------------------
-- Policies
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policies
		(Type,												PolicyBranchType,					BranchPhilosophyTag,				Description,												Help,													 		Civilopedia,													IconAtlas,		 PortraitIndex)
VALUES	--ANCIENT			                            	                                							                            		                                                         		                                                            	              
		('POLICY_JFD_PHILOSOPHY_DENG_XI',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_DENG_XI',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_DENG_XI_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_DENG_XI_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_GORGIAS',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GORGIAS',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_GORGIAS_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_GORGIAS_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MENCIUS',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MENCIUS',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_MENCIUS_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_MENCIUS_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MOZI',						'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MOZI',						'TXT_KEY_POLICY_JFD_PHILOSOPHY_MOZI_HELP',				 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_MOZI_TEXT',						'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_PANINI',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_PANINI',						'TXT_KEY_POLICY_JFD_PHILOSOPHY_PANINI_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_PANINI_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_POLYKLEITOS',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_POLYKLEITOS',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_POLYKLEITOS_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_POLYKLEITOS_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_PROTAGORAS',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_PROTAGORAS',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_PROTAGORAS_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_PROTAGORAS_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_PTAHHOTEP',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_PTAHHOTEP',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_PTAHHOTEP_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_PTAHHOTEP_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_PYTHAGORAS',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_PYTHAGORAS',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_PYTHAGORAS_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_PYTHAGORAS_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_THALES_OF_MILETUS',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_THALES_OF_MILETUS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_THALES_OF_MILETUS_HELP',	 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_THALES_OF_MILETUS_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_VALLUVAR',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_VALLUVAR',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_VALLUVAR_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_VALLUVAR_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_XENOPHANES',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_XENOPHANES',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_XENOPHANES_HELP',			 	'TXT_KEY_POLICY_JFD_PHILOSOPHY_XENOPHANES_TEXT',				'POLICY_ATLAS',  0),
		--CLASSICAL			                            	                                							                                		                                                         		                                                                          
		('POLICY_JFD_PHILOSOPHY_ARISTIPPUS',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARISTIPPUS',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARISTIPPUS_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARISTIPPUS_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ARISTOTLE',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARISTOTLE',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARISTOTLE_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARISTOTLE_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_EPICTETUS',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_EPICTETUS',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_EPICTETUS_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_EPICTETUS_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_GU_KAIZHI',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_GU_KAIZHI',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_GU_KAIZHI_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_GU_KAIZHI_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_HAN_FEI',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_HAN_FEI',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_HAN_FEI_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_HAN_FEI_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ISOCRATES',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ISOCRATES',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_ISOCRATES_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_ISOCRATES_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_NAGARJUNA',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_NAGARJUNA',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_NAGARJUNA_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_NAGARJUNA_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_PLATO',						'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_PLATO',						'TXT_KEY_POLICY_JFD_PHILOSOPHY_PLATO_HELP',				 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_PLATO_TEXT',						'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_PYRRHO',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_PYRRHO',						'TXT_KEY_POLICY_JFD_PHILOSOPHY_PYRRHO_HELP',				 	'TXT_KEY_POLICY_JFD_PHILOSOPHY_PYRRHO_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_QUINTILIAN',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_QUINTILIAN',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_QUINTILIAN_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_QUINTILIAN_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_THUCYDIDES',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_THUCYDIDES',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_THUCYDIDES_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_THUCYDIDES_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ZHUANGZI',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ZHUANGZI',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_ZHUANGZI_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_ZHUANGZI_TEXT',					'POLICY_ATLAS',  0),
		--MEDIEVAL						
		('POLICY_JFD_PHILOSOPHY_ABHINAVAGUPTA',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ABHINAVAGUPTA',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ABHINAVAGUPTA_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_ABHINAVAGUPTA_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_AVERROES',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_AVERROES',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_AVERROES_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_AVERROES_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_AVICENNA',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_AVICENNA',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_AVICENNA_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_AVICENNA_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_BOETHIUS',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_BOETHIUS',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_BOETHIUS_HELP',			 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_BOETHIUS_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_DUNS_SCOTUS',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_DUNS_SCOTUS',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_DUNS_SCOTUS_HELP',			 	'TXT_KEY_POLICY_JFD_PHILOSOPHY_DUNS_SCOTUS_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JALAL_RUMI',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_JALAL_RUMI',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_JALAL_RUMI_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_JALAL_RUMI_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MAIMONIDES',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MAIMONIDES',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_MAIMONIDES_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_MAIMONIDES_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ST_AUGUSTINE',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ST_AUGUSTINE',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ST_AUGUSTINE_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_ST_AUGUSTINE_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_THOMAS_AQUINAS',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_THOMAS_AQUINAS',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_THOMAS_AQUINAS_HELP',	 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_THOMAS_AQUINAS_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_WANG_ANSHI',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_WANG_ANSHI',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_WANG_ANSHI_HELP',			 	'TXT_KEY_POLICY_JFD_PHILOSOPHY_WANG_ANSHI_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_WONHYO',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_WONHYO',						'TXT_KEY_POLICY_JFD_PHILOSOPHY_WONHYO_HELP',	 		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_WONHYO_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ZEAMI_MOTOKIYO',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ZEAMI_MOTOKIYO',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ZEAMI_MOTOKIYO_HELP',	 		 'TXT_KEY_POLICY_JFD_PHILOSOPHY_ZEAMI_MOTOKIYO_TEXT',			'POLICY_ATLAS',  0),
		--RENAISSANCE					
		('POLICY_JFD_PHILOSOPHY_BLAISE_PASCAL',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_BLAISE_PASCAL',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_BLAISE_PASCAL_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_BLAISE_PASCAL_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_FRANCIS_BACON',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_FRANCIS_BACON',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_FRANCIS_BACON_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_FRANCIS_BACON_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_GIORGIO_VASARI',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_GIORGIO_VASARI',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_GIORGIO_VASARI_HELP',			 'TXT_KEY_POLICY_JFD_PHILOSOPHY_GIORGIO_VASARI_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_HUANG_ZONGXI',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_HUANG_ZONGXI',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_HUANG_ZONGXI_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_HUANG_ZONGXI_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_HUGO_GROTIUS',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_HUGO_GROTIUS',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_HUGO_GROTIUS_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_HUGO_GROTIUS_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MACHIAVELLI',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MACHIAVELLI',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_MACHIAVELLI_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_MACHIAVELLI_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MULLA_SADRA',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MULLA_SADRA',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_MULLA_SADRA_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_MULLA_SADRA_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_RENE_DESCARTES',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_RENE_DESCARTES',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_RENE_DESCARTES_HELP',	 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_RENE_DESCARTES_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_SEN_NO_RIKYU',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_SEN_NO_RIKYU',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_SEN_NO_RIKYU_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_SEN_NO_RIKYU_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_THOMAS_HOBBES',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_THOMAS_HOBBES',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_THOMAS_HOBBES_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_THOMAS_HOBBES_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_THOMAS_MORE',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_THOMAS_MORE',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_THOMAS_MORE_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_THOMAS_MORE_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ZERA_YACOB',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ZERA_YACOB',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_ZERA_YACOB_HELP',		 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_ZERA_YACOB_TEXT',				'POLICY_ATLAS',  0),
		--ENLIGHTENMENT					
		('POLICY_JFD_PHILOSOPHY_ADAM_SMITH',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ADAM_SMITH',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_ADAM_SMITH_HELP',	 			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ADAM_SMITH_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_BAK_JIWON',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_BAK_JIWON',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_BAK_JIWON_HELP',	 				'TXT_KEY_POLICY_JFD_PHILOSOPHY_BAK_JIWON_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_DAVID_HUME',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_DAVID_HUME',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_DAVID_HUME_HELP',	 			'TXT_KEY_POLICY_JFD_PHILOSOPHY_DAVID_HUME_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_EDMUND_BURKE',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_EDMUND_BURKE',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_EDMUND_BURKE_HELP',	 			'TXT_KEY_POLICY_JFD_PHILOSOPHY_EDMUND_BURKE_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_FREIDRICH_SCHILLER',		'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_FREIDRICH_SCHILLER',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_FREIDRICH_SCHILLER_HELP',	 	'TXT_KEY_POLICY_JFD_PHILOSOPHY_FREIDRICH_SCHILLER_TEXT',		'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_GOTTFRIED_LEIBNIZ',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GOTTFRIED_LEIBNIZ',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GOTTFRIED_LEIBNIZ_HELP',	 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_GOTTFRIED_LEIBNIZ_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_IMMANUEL_KANT',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_IMMANUEL_KANT',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_IMMANUEL_KANT_HELP',	 			'TXT_KEY_POLICY_JFD_PHILOSOPHY_IMMANUEL_KANT_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JEAN_JACQUES_ROUSSEAU',		'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JEAN_JACQUES_ROUSSEAU',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_JEAN_JACQUES_ROUSSEAU_HELP',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_JEAN_JACQUES_ROUSSEAU_TEXT',		'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JOHN_LOCKE',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_LOCKE',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_LOCKE_HELP',	 			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_LOCKE_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MONTESQUIEU',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MONTESQUIEU',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_MONTESQUIEU_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_MONTESQUIEU_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MOTOORI_NORINAGA',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MOTOORI_NORINAGA',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MOTOORI_NORINAGA_HELP',	 		'TXT_KEY_POLICY_JFD_PHILOSOPHY_MOTOORI_NORINAGA_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_VOLTAIRE',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_VOLTAIRE',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_VOLTAIRE_HELP',	 				'TXT_KEY_POLICY_JFD_PHILOSOPHY_VOLTAIRE_TEXT',					'POLICY_ATLAS',  0),
		--INDUSTRIAL				
		('POLICY_JFD_PHILOSOPHY_ALEXIS_DE_TOCQUEVILLE',		'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ALEXIS_DE_TOCQUEVILLE',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_ALEXIS_DE_TOCQUEVILLE_HELP',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_ALEXIS_DE_TOCQUEVILLE_TEXT',		'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_AUGUSTE_COMTE',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_AUGUSTE_COMTE',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_AUGUSTE_COMTE_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_AUGUSTE_COMTE_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_CARL_VON_CLAUSEWITZ',		'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_CARL_VON_CLAUSEWITZ',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_CARL_VON_CLAUSEWITZ_HELP',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_CARL_VON_CLAUSEWITZ_TEXT',		'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_FERDINAND_DE_SAUSSURE',		'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_FERDINAND_DE_SAUSSURE',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_FERDINAND_DE_SAUSSURE_HELP',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_FERDINAND_DE_SAUSSURE_TEXT',		'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE',		'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE_HELP',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE_TEXT',		'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_GEORG_F_W_HEGEL',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GEORG_F_W_HEGEL',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GEORG_F_W_HEGEL_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GEORG_F_W_HEGEL_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JOHN_STUART_MILL',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_STUART_MILL',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_STUART_MILL_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_STUART_MILL_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_KARL_MARX',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_KARL_MARX',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_KARL_MARX_HELP',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_KARL_MARX_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MOHAMMAD_ABDUH',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MOHAMMAD_ABDUH',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_MOHAMMAD_ABDUH_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MOHAMMAD_ABDUH_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_SOREN_KIERKEGAARD',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_SOREN_KIERKEGAARD',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_SOREN_KIERKEGAARD_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_SOREN_KIERKEGAARD_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_SWAMI_VIVEKANANDA',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_SWAMI_VIVEKANANDA',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_SWAMI_VIVEKANANDA_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_SWAMI_VIVEKANANDA_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_VLADIMIR_DAL',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_VLADIMIR_DAL',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_VLADIMIR_DAL_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_VLADIMIR_DAL_TEXT',				'POLICY_ATLAS',  0),
		--MODERN				
		('POLICY_JFD_PHILOSOPHY_AYN_RAND',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_AYN_RAND',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_AYN_RAND_HELP',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_AYN_RAND_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_BERTRAND_RUSSELL',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_BERTRAND_RUSSELL',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_BERTRAND_RUSSELL_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_BERTRAND_RUSSELL_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_CHARLES_MAURRAS',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_CHARLES_MAURRAS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_CHARLES_MAURRAS_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_CHARLES_MAURRAS_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_EMILE_DURKHEIM',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_EMILE_DURKHEIM',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_EMILE_DURKHEIM_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_EMILE_DURKHEIM_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_GIOVANNI_GENTILE',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GIOVANNI_GENTILE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GIOVANNI_GENTILE_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GIOVANNI_GENTILE_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JEAN_PAUL_SATRE',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JEAN_PAUL_SATRE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JEAN_PAUL_SATRE_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JEAN_PAUL_SATRE_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JOHN_DEWEY',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_DEWEY',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_DEWEY_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_DEWEY_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MARTIN_HEIDEGGER',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MARTIN_HEIDEGGER',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MARTIN_HEIDEGGER_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MARTIN_HEIDEGGER_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MAX_WEBER',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MAX_WEBER',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_MAX_WEBER_HELP',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_MAX_WEBER_TEXT',					'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_TETSURO_WATSUJI',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_TETSURO_WATSUJI',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_TETSURO_WATSUJI_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_TETSURO_WATSUJI_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_RABINDRANATH_TAGORE',		'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_RABINDRANATH_TAGORE',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_RABINDRANATH_TAGORE_HELP',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_RABINDRANATH_TAGORE_TEXT',		'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_WALTER_BENJAMIN',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_WALTER_BENJAMIN',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_WALTER_BENJAMIN_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_WALTER_BENJAMIN_TEXT',			'POLICY_ATLAS',  0),
		--ATOMIC		
		('POLICY_JFD_PHILOSOPHY_ABDUL_MAUDUDI',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ABDUL_MAUDUDI',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ABDUL_MAUDUDI_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ABDUL_MAUDUDI_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ALBERT_CAMUS',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ALBERT_CAMUS',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ALBERT_CAMUS_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ALBERT_CAMUS_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_GUY_DEBORD',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_GUY_DEBORD',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_GUY_DEBORD_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_GUY_DEBORD_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_HANS_MORGENTHAU',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_HANS_MORGENTHAU',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_HANS_MORGENTHAU_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_HANS_MORGENTHAU_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ISAIAH_BERLIN',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ISAIAH_BERLIN',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ISAIAH_BERLIN_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ISAIAH_BERLIN_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JOHN_MAYNARD_KEYNES',		'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_MAYNARD_KEYNES',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_MAYNARD_KEYNES_HELP',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_MAYNARD_KEYNES_TEXT',		'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JOHN_RAWLS',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_RAWLS',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_RAWLS_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_RAWLS_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_KARL_POPPER',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_KARL_POPPER',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_KARL_POPPER_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_KARL_POPPER_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MARSHALL_MCLUHAN',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_MARSHALL_MCLUHAN',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MARSHALL_MCLUHAN_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MARSHALL_MCLUHAN_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_MICHEL_FOUCAULT',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MICHEL_FOUCAULT',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MICHEL_FOUCAULT_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_MICHEL_FOUCAULT_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_SIMONE_DE_BEAUVOIR',		'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_SIMONE_DE_BEAUVOIR',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_SIMONE_DE_BEAUVOIR_HELP',		'TXT_KEY_POLICY_JFD_PHILOSOPHY_SIMONE_DE_BEAUVOIR_TEXT',		'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_XU_FUGUAN',					'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_XU_FUGUAN',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_XU_FUGUAN_HELP',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_XU_FUGUAN_TEXT',					'POLICY_ATLAS',  0),
		--INFORMATION		
		('POLICY_JFD_PHILOSOPHY_ARNE_NAESS',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARNE_NAESS',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARNE_NAESS_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARNE_NAESS_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ENRIQUE_DUSSELL',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ENRIQUE_DUSSELL',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ENRIQUE_DUSSELL_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_ENRIQUE_DUSSELL_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_HENRY_ODERA_ORUKA',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_HENRY_ODERA_ORUKA',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_HENRY_ODERA_ORUKA_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_HENRY_ODERA_ORUKA_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JIANG_QING',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JIANG_QING',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_JIANG_QING_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_JIANG_QING_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JOHN_MEARSHEIMER',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_MEARSHEIMER',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_MEARSHEIMER_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOHN_MEARSHEIMER_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JOSEPH_NYE',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_POLITICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOSEPH_NYE',					'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOSEPH_NYE_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_JOSEPH_NYE_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JUDITH_BUTLER',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JUDITH_BUTLER',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_JUDITH_BUTLER_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_JUDITH_BUTLER_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_JURGEN_HABERMAS',			'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_RHETORIC',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JURGEN_HABERMAS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JURGEN_HABERMAS_HELP',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_JURGEN_HABERMAS_TEXT',			'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_ROGER_SCRUTON',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ART',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ROGER_SCRUTON',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ROGER_SCRUTON_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_ROGER_SCRUTON_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_SLAVOJ_ZIZEK',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_REALITY',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_SLAVOJ_ZIZEK',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_SLAVOJ_ZIZEK_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_SLAVOJ_ZIZEK_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_STUART_HALL',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_KNOWLEDGE',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_STUART_HALL',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_STUART_HALL_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_STUART_HALL_TEXT',				'POLICY_ATLAS',  0),
		('POLICY_JFD_PHILOSOPHY_WILL_KYMLICKA',				'POLICY_BRANCH_JFD_PHILOSOPHY',		'PHILOSOPHY_JFD_ETHICS',			'TXT_KEY_POLICY_JFD_PHILOSOPHY_WILL_KYMLICKA',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_WILL_KYMLICKA_HELP',				'TXT_KEY_POLICY_JFD_PHILOSOPHY_WILL_KYMLICKA_TEXT',				'POLICY_ATLAS',  0);
		
UPDATE Policies
SET Help = 'TXT_KEY_POLICY_JFD_PHILOSOPHY_ADAM_SMITH_HELP_WEIGH_HOUSE'
WHERE Type = 'POLICY_JFD_PHILOSOPHY_ADAM_SMITH'
AND EXISTS (SELECT Type FROM Buildings WHERE Type = 'BUILDING_EE_WEIGH_HOUSE');

UPDATE Policies
SET HappinessToCulture = 15
WHERE Type = 'POLICY_JFD_PHILOSOPHY_ALBERT_CAMUS';	

UPDATE Policies
SET HappinessPerTradeRoute = 100
WHERE Type = 'POLICY_JFD_PHILOSOPHY_ALEXIS_DE_TOCQUEVILLE';	

UPDATE Policies
SET HappfromXSpecialists = 4
WHERE Type = 'POLICY_JFD_PHILOSOPHY_AYN_RAND';	

UPDATE Policies
SET GreatScientistRateModifier = 25, GreatScientistBeakerModifier = 25
WHERE Type = 'POLICY_JFD_PHILOSOPHY_BERTRAND_RUSSELL';	

UPDATE Policies
SET GreatGeneralExtraBonus = 10, CultureBombBoost = 1
WHERE Type = 'POLICY_JFD_PHILOSOPHY_CARL_VON_CLAUSEWITZ';	

UPDATE Policies
SET PolicyCostModifier = -15
WHERE Type = 'POLICY_JFD_PHILOSOPHY_CHARLES_MAURRAS';	

UPDATE Policies
SET SharedReligionTourismModifier = 10, LessHappyTourismModifier = 10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_ENRIQUE_DUSSELL';	

UPDATE Policies
SET Help = 'TXT_KEY_POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE_HELP_DIRECTOR'
WHERE Type = 'POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE'
AND EXISTS (SELECT Type FROM Specialists WHERE Type = 'SPECIALIST_JFD_DIRECTOR');

UPDATE Policies
SET GoldenAgeTurns = 10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_GEORG_F_W_HEGEL';	

UPDATE Policies
SET GoldenAgeTurns = 10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_GIORGIO_VASARI';

UPDATE Policies
SET HappinessPerXGreatWorks = 4
WHERE Type = 'POLICY_JFD_PHILOSOPHY_GUY_DEBORD';

UPDATE Policies
SET AfraidMinorPerTurnInfluence = 1
WHERE Type = 'POLICY_JFD_PHILOSOPHY_HANS_MORGENTHAU';	

UPDATE Policies
SET ProtectedMinorPerTurnInfluence = 100
WHERE Type = 'POLICY_JFD_PHILOSOPHY_HUGO_GROTIUS';	

UPDATE Policies
SET Help = 'TXT_KEY_POLICY_JFD_PHILOSOPHY_JALAL_RUMI_HELP_PERFORMER'
WHERE Type = 'POLICY_JFD_PHILOSOPHY_JALAL_RUMI'
AND EXISTS (SELECT Type FROM Specialists WHERE Type = 'SPECIALIST_JFD_PERFORMER');

UPDATE Policies
SET UnhappinessMod = -10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_JOHN_RAWLS';

UPDATE Policies
SET ExtraHappinessPerLuxury = 1
WHERE Type = 'POLICY_JFD_PHILOSOPHY_JOHN_STUART_MILL';

UPDATE Policies
SET CommonFoeTourismModifier = 20
WHERE Type = 'POLICY_JFD_PHILOSOPHY_JOHN_MEARSHEIMER';

UPDATE Policies
SET TradeRouteTourismModifier = 10, OpenBordersTourismModifier = 10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_JOSEPH_NYE';

UPDATE Policies
SET GreatWriterRateModifier = 10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_MOTOORI_NORINAGA';	

UPDATE Policies
SET GoldenAgeTurns = 10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_MULLA_SADRA';	

UPDATE Policies
SET GoldenAgeTurns = 20
WHERE Type = 'POLICY_JFD_PHILOSOPHY_NAGARJUNA';

UPDATE Policies
SET PlotCultureExponentModifier = 15
WHERE Type = 'POLICY_JFD_PHILOSOPHY_PROTAGORAS';

UPDATE Policies
SET ThemingBonusMultiplier = 50
WHERE Type = 'POLICY_JFD_PHILOSOPHY_RABINDRANATH_TAGORE';	

UPDATE Policies
SET CultureWonderMultiplier = 17
WHERE Type = 'POLICY_JFD_PHILOSOPHY_ROGER_SCRUTIN';	

UPDATE Policies
SET NoUnhappfromXSpecialists = 4
WHERE Type = 'POLICY_JFD_PHILOSOPHY_SIMONE_DE_BEAUVOIR';	

UPDATE Policies
SET SharedIdeologyTourismModifier = 20
WHERE Type = 'POLICY_JFD_PHILOSOPHY_SLAVOJ_ZIZEK';		

UPDATE Policies
SET GoldenAgeMeterMod = -25
WHERE Type = 'POLICY_JFD_PHILOSOPHY_TETSURO_WATSUJI';		

UPDATE Policies
SET IncludesOneShotFreeUnits = 1
WHERE Type = 'POLICY_JFD_PHILOSOPHY_THALES_OF_MILETUS';	

UPDATE Policies
SET GarrisonsOccupiedUnhapppinessMod = -33
WHERE Type = 'POLICY_JFD_PHILOSOPHY_THOMAS_HOBBES';

UPDATE Policies
SET BarbarianCombatBonus = 10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_THUCYDIDES';	

UPDATE Policies
SET InternalTradeRouteYieldModifier = 10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_WANG_ANSHI';	

UPDATE Policies
SET Help = 'TXT_KEY_POLICY_JFD_PHILOSOPHY_VOLTAIRE_HELP_SALON'
WHERE Type = 'POLICY_JFD_PHILOSOPHY_VOLTAIRE'
AND EXISTS (SELECT Type FROM BuildingClasses WHERE Type = 'BUILDINGCLASS_EE_SALON');

UPDATE Policies
SET InfluenceGPExpend = 10
WHERE Type = 'POLICY_JFD_PHILOSOPHY_ZERA_YACOB';	
--------------------------------------------------------------------------------------------------------------------------
-- Policy_ArtYieldChanges
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_ArtYieldChanges
		(PolicyType,									YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_WALTER_BENJAMIN',		'YIELD_CULTURE',			1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_BuildingClassHappiness
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_BuildingClassHappiness
		(PolicyType,								BuildingClassType,					Happiness)
VALUES	('POLICY_JFD_PHILOSOPHY_ABHINAVAGUPTA',		'BUILDINGCLASS_ARTISTS_GUILD',		1),
		('POLICY_JFD_PHILOSOPHY_ABHINAVAGUPTA',		'BUILDINGCLASS_MUSICIANS_GUILD',	1),
		('POLICY_JFD_PHILOSOPHY_ABHINAVAGUPTA',		'BUILDINGCLASS_WRITERS_GUILD',		1),
		('POLICY_JFD_PHILOSOPHY_GIOVANNI_GENTILE',	'BUILDINGCLASS_POLICE_STATION',		1),
		('POLICY_JFD_PHILOSOPHY_MENCIUS',			'BUILDINGCLASS_PALACE',		 		1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_BuildingClassProductionModifiers
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_BuildingClassProductionModifiers
		(PolicyType,								BuildingClassType,					ProductionModifier)
VALUES	('POLICY_JFD_PHILOSOPHY_ADAM_SMITH',		'BUILDINGCLASS_BANK',				20),
		('POLICY_JFD_PHILOSOPHY_ADAM_SMITH',		'BUILDINGCLASS_MARKET',				20),
		('POLICY_JFD_PHILOSOPHY_ARISTIPPUS',		'BUILDINGCLASS_CIRCUS',				10),
		('POLICY_JFD_PHILOSOPHY_ARISTIPPUS',		'BUILDINGCLASS_COLOSSEUM',			10),
		('POLICY_JFD_PHILOSOPHY_ARNE_NAESS',		'BUILDINGCLASS_RECYCLING_CENTER',	25),
		('POLICY_JFD_PHILOSOPHY_ARNE_NAESS',		'BUILDINGCLASS_SOLAR_PLANT',		25),
		('POLICY_JFD_PHILOSOPHY_EPICTETUS',			'BUILDINGCLASS_COURTHOUSE',			10),
		('POLICY_JFD_PHILOSOPHY_FRANCIS_BACON',		'BUILDINGCLASS_OBSERVATORY',		50),
		('POLICY_JFD_PHILOSOPHY_GIOVANNI_GENTILE',	'BUILDINGCLASS_POLICE_STATION',		25),
		('POLICY_JFD_PHILOSOPHY_JOHN_LOCKE',		'BUILDINGCLASS_PUBLIC_SCHOOL',		15),
		('POLICY_JFD_PHILOSOPHY_JOHN_MEARSHEIMER',	'BUILDINGCLASS_BOMB_SHELTER',		15),
		('POLICY_JFD_PHILOSOPHY_JOHN_MEARSHEIMER',	'BUILDINGCLASS_NUCLEAR_PLANT',		15),
		('POLICY_JFD_PHILOSOPHY_MACHIAVELLI',		'BUILDINGCLASS_CONSTABLE',			15),
		('POLICY_JFD_PHILOSOPHY_MOZI',				'BUILDINGCLASS_GRANARY',			10),
		('POLICY_JFD_PHILOSOPHY_QUINTILIAN',		'BUILDINGCLASS_AMPHITHEATER',		10),
		('POLICY_JFD_PHILOSOPHY_QUINTILIAN',		'BUILDINGCLASS_MARKET',				10),
		('POLICY_JFD_PHILOSOPHY_PANINI',			'BUILDINGCLASS_LIBRARY',			10),
		('POLICY_JFD_PHILOSOPHY_THOMAS_AQUINAS',	'BUILDINGCLASS_LIBRARY',			15),
		('POLICY_JFD_PHILOSOPHY_THOMAS_AQUINAS',	'BUILDINGCLASS_UNIVERSITY',			15),
		('POLICY_JFD_PHILOSOPHY_VALLUVAR',			'BUILDINGCLASS_MONUMENT',			15),
		('POLICY_JFD_PHILOSOPHY_VOLTAIRE',			'BUILDINGCLASS_PUBLIC_SCHOOL',		20),
		('POLICY_JFD_PHILOSOPHY_ZEAMI_MOTOKIYO',	'BUILDINGCLASS_ARTISTS_GUILD',		20),
		('POLICY_JFD_PHILOSOPHY_ZEAMI_MOTOKIYO',	'BUILDINGCLASS_MUSICIANS_GUILD',	20),
		('POLICY_JFD_PHILOSOPHY_ZEAMI_MOTOKIYO',	'BUILDINGCLASS_WRITERS_GUILD',		20);
		
INSERT INTO Policy_BuildingClassProductionModifiers
		(PolicyType,								BuildingClassType,				ProductionModifier)
SELECT	'POLICY_JFD_PHILOSOPHY_ADAM_SMITH',			Type,							20
FROM BuildingClasses WHERE Type = 'BUILDINGCLASS_EE_WEIGH_HOUSE';
		
INSERT INTO Policy_BuildingClassProductionModifiers
		(PolicyType,								BuildingClassType,				ProductionModifier)
SELECT	'POLICY_JFD_PHILOSOPHY_ARNE_NAESS',			Type,							25
FROM BuildingClasses WHERE Type IN ('BUILDINGCLASS_JFD_WIND_FARM');
				
INSERT INTO Policy_BuildingClassProductionModifiers
		(PolicyType,								BuildingClassType,				ProductionModifier)
SELECT	'POLICY_JFD_PHILOSOPHY_MONTESQUIEU',		Type,							15
FROM BuildingClasses WHERE MaxPlayerInstances = 1;
		
INSERT INTO Policy_BuildingClassProductionModifiers
		(PolicyType,								BuildingClassType,				ProductionModifier)
SELECT	'POLICY_JFD_PHILOSOPHY_MONTESQUIEU',		BuildingClassType,				15
FROM Building_PrereqBuildingClasses WHERE NumBuildingNeeded = -1;

UPDATE Policy_BuildingClassProductionModifiers
SET BuildingClassType = 'BUILDINGCLASS_EE_SALON'
WHERE PolicyType = 'POLICY_JFD_PHILOSOPHY_VOLTAIRE' AND BuildingClassType = 'BUILDINGCLASS_PUBLIC_SCHOOL'
AND EXISTS (SELECT Type FROM BuildingClasses WHERE Type = 'BUILDINGCLASS_EE_SALON');

INSERT INTO Policy_BuildingClassProductionModifiers
		(PolicyType,								BuildingClassType,				ProductionModifier)
SELECT	'POLICY_JFD_PHILOSOPHY_ZEAMI_MOTOKIYO',		Type,							20
FROM BuildingClasses WHERE Type IN ('BUILDINGCLASS_JFD_DIRECTORS_GUILD', 'BUILDINGCLASS_JFD_PERFORMERS_GUILD');
--------------------------------------------------------------------------------------------------------------------------
-- Policy_BuildingClassYieldChanges
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_BuildingClassYieldChanges
		(PolicyType,								BuildingClassType,				YieldType,					YieldChange)
VALUES	('POLICY_JFD_PHILOSOPHY_ABDUL_MAUDUDI',		'BUILDINGCLASS_CONSTABLE',		'YIELD_FAITH',				2),
		('POLICY_JFD_PHILOSOPHY_ABDUL_MAUDUDI',		'BUILDINGCLASS_COURTHOUSE',		'YIELD_FAITH',				2),
		('POLICY_JFD_PHILOSOPHY_ABDUL_MAUDUDI',		'BUILDINGCLASS_POLICE_STATION',	'YIELD_FAITH',				2),
		('POLICY_JFD_PHILOSOPHY_BLAISE_PASCAL',		'BUILDINGCLASS_OBSERVATORY',	'YIELD_FAITH',				2),
		('POLICY_JFD_PHILOSOPHY_BLAISE_PASCAL',		'BUILDINGCLASS_UNIVERSITY',		'YIELD_FAITH',				2),
		('POLICY_JFD_PHILOSOPHY_DENG_XI',			'BUILDINGCLASS_PALACE',			'YIELD_PRODUCTION',			2),
		('POLICY_JFD_PHILOSOPHY_GU_KAIZHI',			'BUILDINGCLASS_PALACE',			'YIELD_CULTURE',			2),
		('POLICY_JFD_PHILOSOPHY_GU_KAIZHI',			'BUILDINGCLASS_PALACE',			'YIELD_GOLDEN_AGE_POINTS',	1),
		('POLICY_JFD_PHILOSOPHY_HAN_FEI',			'BUILDINGCLASS_COURTHOUSE',		'YIELD_GOLD',				1),
		('POLICY_JFD_PHILOSOPHY_HAN_FEI',			'BUILDINGCLASS_COURTHOUSE',		'YIELD_PRODUCTION',			1),
		('POLICY_JFD_PHILOSOPHY_ISOCRATES',			'BUILDINGCLASS_AMPHITHEATER',	'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_JOHN_LOCKE',		'BUILDINGCLASS_PUBLIC_SCHOOL',	'YIELD_SCIENCE',			1),
		('POLICY_JFD_PHILOSOPHY_MACHIAVELLI',		'BUILDINGCLASS_CONSTABLE',		'YIELD_PRODUCTION',			2),
		('POLICY_JFD_PHILOSOPHY_PLATO',				'BUILDINGCLASS_AMPHITHEATER',	'YIELD_SCIENCE',			1),
		('POLICY_JFD_PHILOSOPHY_POLYKLEITOS',		'BUILDINGCLASS_STONE_WORKS',	'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_PTAHHOTEP',			'BUILDINGCLASS_PALACE',			'YIELD_SCIENCE',			1),
		('POLICY_JFD_PHILOSOPHY_SEN_NO_RIKYU',		'BUILDINGCLASS_GARDEN',			'YIELD_CULTURE',			2),
		('POLICY_JFD_PHILOSOPHY_SEN_NO_RIKYU',		'BUILDINGCLASS_GARDEN',			'YIELD_GOLDEN_AGE_POINTS',	1),
		('POLICY_JFD_PHILOSOPHY_STUART_HALL',		'BUILDINGCLASS_LABORATORY',		'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_VOLTAIRE',			'BUILDINGCLASS_PUBLIC_SCHOOL',	'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_WONHYO',			'BUILDINGCLASS_UNIVERSITY',		'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_WONHYO',			'BUILDINGCLASS_UNIVERSITY',		'YIELD_SCIENCE',			1),
		('POLICY_JFD_PHILOSOPHY_XENOPHANES',		'BUILDINGCLASS_LIBRARY',		'YIELD_GOLDEN_AGE_POINTS',	2);

INSERT INTO Policy_BuildingClassYieldChanges
		(PolicyType,								BuildingClassType,				YieldType,					YieldChange)
SELECT	'POLICY_JFD_PHILOSOPHY_JIANG_QING',			Type,							'YIELD_CULTURE',			2
FROM BuildingClasses WHERE MaxPlayerInstances = 1;

INSERT INTO Policy_BuildingClassYieldChanges
		(PolicyType,								BuildingClassType,				YieldType,					YieldChange)
SELECT	'POLICY_JFD_PHILOSOPHY_JIANG_QING',			Type,							'YIELD_FAITH',				2
FROM BuildingClasses WHERE MaxPlayerInstances = 1;
		
INSERT INTO Policy_BuildingClassYieldChanges
		(PolicyType,								BuildingClassType,				YieldType,					YieldChange)
SELECT	'POLICY_JFD_PHILOSOPHY_MOHAMMAD_ABDUH',		BuildingClass,					'YIELD_FAITH',				2
FROM Buildings WHERE Cost = -1 AND FaithCost > 0 AND UnlockedByBelief = 1;
		
INSERT INTO Policy_BuildingClassYieldChanges
		(PolicyType,								BuildingClassType,				YieldType,					YieldChange)
SELECT	'POLICY_JFD_PHILOSOPHY_MOHAMMAD_ABDUH',		BuildingClass,					'YIELD_SCIENCE',			2
FROM Buildings WHERE Cost = -1 AND FaithCost > 0 AND UnlockedByBelief = 1;

INSERT INTO Policy_BuildingClassYieldChanges
		(PolicyType,								BuildingClassType,				YieldType,					YieldChange)
SELECT	'POLICY_JFD_PHILOSOPHY_THOMAS_MORE',		Type,							'YIELD_GOLDEN_AGE_POINTS',	2
FROM BuildingClasses WHERE MaxPlayerInstances = 1;

UPDATE Policy_BuildingClassYieldChanges
SET BuildingClassType = 'BUILDINGCLASS_EE_SALON'
WHERE PolicyType = 'POLICY_JFD_PHILOSOPHY_VOLTAIRE' AND BuildingClassType = 'BUILDINGCLASS_PUBLIC_SCHOOL'
AND EXISTS (SELECT Type FROM BuildingClasses WHERE Type = 'BUILDINGCLASS_EE_SALON');
--------------------------------------------------------------------------------------------------------------------------
-- Policy_BuildingClassYieldModifiers
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_BuildingClassYieldModifiers
		(PolicyType,								BuildingClassType,				YieldType,				YieldMod)
VALUES	('POLICY_JFD_PHILOSOPHY_STUART_HALL',		'BUILDINGCLASS_LABORATORY',		'YIELD_CULTURE',		20);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_CapitalYieldPerPopChangeEmpire
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_CapitalYieldPerPopChangeEmpire
		(PolicyType,								YieldType,		Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_EDMUND_BURKE',		'YIELD_GOLD',	20);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_FilmYieldChanges
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_FilmYieldChanges
		(PolicyType,								YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_WALTER_BENJAMIN',	'YIELD_CULTURE',			1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_GoldenAgeYieldMod
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_GoldenAgeYieldMod
		(PolicyType,								YieldType,			Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_GEORG_F_W_HEGEL',	'YIELD_CULTURE',	15),
		('POLICY_JFD_PHILOSOPHY_MULLA_SADRA',		'YIELD_FAITH',		10);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_GoldenAgeGreatPersonRateModifier
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_GoldenAgeGreatPersonRateModifier
		(PolicyType,								GreatPersonType, 		Modifier)
VALUES	('POLICY_JFD_PHILOSOPHY_GIORGIO_VASARI',	'GREATPERSON_ARTIST',	10),
		('POLICY_JFD_PHILOSOPHY_GIORGIO_VASARI',	'GREATPERSON_ENGINEER',	10),
		('POLICY_JFD_PHILOSOPHY_GIORGIO_VASARI',	'GREATPERSON_WRITER',	10);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_GreatPersonExpendedYield
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_GreatPersonExpendedYield
		(PolicyType,								GreatPersonType, 		YieldType, 			Yield)
VALUEs	('POLICY_JFD_PHILOSOPHY_MARTIN_HEIDEGGER',	'GREATPERSON_WRITER',	'YIELD_CULTURE',    50);

INSERT INTO Policy_GreatPersonExpendedYield
		(PolicyType,								GreatPersonType, 	YieldType, 				  		Yield)
SELECT	'POLICY_JFD_PHILOSOPHY_PYRRHO',				Type,	 		 	'YIELD_GOLDEN_AGE_POINTS',   	50
FROM GreatPersons;		
		
INSERT INTO Policy_GreatPersonExpendedYield		
		(PolicyType,								GreatPersonType, 	YieldType, 						Yield)
SELECT	'POLICY_JFD_PHILOSOPHY_RENE_DESCARTES',		Type,	 		 	'YIELD_SCIENCE', 				25
FROM GreatPersons;				
				
INSERT INTO Policy_GreatPersonExpendedYield				
		(PolicyType,								GreatPersonType, 	YieldType, 	 					Yield)
SELECT	'POLICY_JFD_PHILOSOPHY_SOREN_KIERKEGAARD',	Type,	 		 	'YIELD_FAITH',  				100
FROM GreatPersons;
--------------------------------------------------------------------------------------------------------------------------
-- Policy_GreatWorkYieldChanges
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_GreatWorkYieldChanges
		(PolicyType,									YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_JUDITH_BUTLER',			'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_JUDITH_BUTLER',			'YIELD_TOURISM',			1),
		('POLICY_JFD_PHILOSOPHY_MARSHALL_MCLUHAN',		'YIELD_SCIENCE',			1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_LitYieldChanges
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_LitYieldChanges
		(PolicyType,									YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_BOETHIUS',				'YIELD_SCIENCE',			1),
		('POLICY_JFD_PHILOSOPHY_HUANG_ZONGXI',			'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_HUANG_ZONGXI',			'YIELD_GOLDEN_AGE_POINTS',	1),
		('POLICY_JFD_PHILOSOPHY_MARTIN_HEIDEGGER',		'YIELD_CULTURE',			1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_ImprovementYieldChanges
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_ImprovementYieldChanges
		(PolicyType,								ImprovementType,			YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_ARISTOTLE',			'IMPROVEMENT_ACADEMY',		'YIELD_SCIENCE',			2),
		('POLICY_JFD_PHILOSOPHY_AVICENNA',			'IMPROVEMENT_ACADEMY',		'YIELD_FAITH',				2),
		('POLICY_JFD_PHILOSOPHY_AVICENNA',			'IMPROVEMENT_ACADEMY',		'YIELD_SCIENCE',			2),
		('POLICY_JFD_PHILOSOPHY_AUGUSTE_COMTE',		'IMPROVEMENT_ACADEMY',		'YIELD_CULTURE',			3),
		('POLICY_JFD_PHILOSOPHY_AUGUSTE_COMTE',		'IMPROVEMENT_ACADEMY',		'YIELD_SCIENCE',			2),
		('POLICY_JFD_PHILOSOPHY_DUNS_SCOTUS',		'IMPROVEMENT_HOLY_SITE',	'YIELD_FAITH',				2),
		('POLICY_JFD_PHILOSOPHY_DUNS_SCOTUS',		'IMPROVEMENT_HOLY_SITE',	'YIELD_GOLDEN_AGE_POINTS',	2),
		('POLICY_JFD_PHILOSOPHY_EMILE_DURKHEIM',	'IMPROVEMENT_HOLY_SITE',	'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_EMILE_DURKHEIM',	'IMPROVEMENT_HOLY_SITE',	'YIELD_SCIENCE',			2),
		('POLICY_JFD_PHILOSOPHY_EMILE_DURKHEIM',	'IMPROVEMENT_LANDMARK',		'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_EMILE_DURKHEIM',	'IMPROVEMENT_LANDMARK',		'YIELD_SCIENCE',			2);

INSERT INTO Policy_ImprovementYieldChanges
		(PolicyType,									ImprovementType, YieldType,						Yield)
SELECT	'POLICY_JFD_PHILOSOPHY_DAVID_HUME',				Type, 			 'YIELD_GOLDEN_AGE_POINTS', 	2
FROM Improvements WHERE CreatedByGreatPerson = 1;

INSERT INTO Policy_ImprovementYieldChanges
		(PolicyType,									ImprovementType, YieldType,			Yield)
SELECT	'POLICY_JFD_PHILOSOPHY_DAVID_HUME',				Type, 			 'YIELD_CULTURE', 	1
FROM Improvements WHERE CreatedByGreatPerson = 1;

INSERT INTO Policy_ImprovementYieldChanges
		(PolicyType,									ImprovementType, YieldType,		  	Yield)
SELECT	'POLICY_JFD_PHILOSOPHY_HENRY_ODERA_ORUKA',		Type, 			 'YIELD_CULTURE', 	2
FROM Improvements WHERE CreatedByGreatPerson = 1;	
	
INSERT INTO Policy_ImprovementYieldChanges	
		(PolicyType,									ImprovementType, YieldType,		  	Yield)
SELECT	'POLICY_JFD_PHILOSOPHY_HENRY_ODERA_ORUKA',		Type, 			 'YIELD_TOURISM', 	2
FROM Improvements WHERE CreatedByGreatPerson = 1;

INSERT INTO Policy_ImprovementYieldChanges
		(PolicyType,									ImprovementType, YieldType,			Yield)
SELECT	'POLICY_JFD_PHILOSOPHY_ST_AUGUSTINE',			Type, 			 'YIELD_FAITH', 	1
FROM Improvements WHERE CreatedByGreatPerson = 1;
--------------------------------------------------------------------------------------------------------------------------
-- Policy_MusicYieldChanges
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_MusicYieldChanges
		(PolicyType,									YieldType,				Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_WALTER_BENJAMIN',		'YIELD_CULTURE',		1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_SpecialistYieldChanges
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_SpecialistExtraYields
		(PolicyType,								YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_KARL_POPPER',		'YIELD_SCIENCE',			1),
		('POLICY_JFD_PHILOSOPHY_ISAIAH_BERLIN',		'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_JEAN_PAUL_SATRE',	'YIELD_GOLDEN_AGE_POINTS',	1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_SpecialistYieldChanges
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_SpecialistYieldChanges
		(PolicyType,									SpecialistType,				YieldType,						Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_AVERROES',				'SPECIALIST_WRITER',		'YIELD_CULTURE',				1),
		('POLICY_JFD_PHILOSOPHY_AVERROES',				'SPECIALIST_WRITER',		'YIELD_GOLDEN_AGE_POINTS',		2),
		('POLICY_JFD_PHILOSOPHY_BAK_JIWON',				'SPECIALIST_SCIENTIST',		'YIELD_FOOD',					1),
		('POLICY_JFD_PHILOSOPHY_BAK_JIWON',				'SPECIALIST_SCIENTIST',		'YIELD_PRODUCTION',				1),
		('POLICY_JFD_PHILOSOPHY_FERDINAND_DE_SAUSSURE',	'SPECIALIST_SCIENTIST',		'YIELD_CULTURE',				2),
		('POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE',	'SPECIALIST_ARTIST',		'YIELD_GOLDEN_AGE_POINTS',		2),
		('POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE',	'SPECIALIST_MUSICIAN',		'YIELD_GOLDEN_AGE_POINTS',		2),
		('POLICY_JFD_PHILOSOPHY_GOTTFRIED_LEIBNIZ',		'SPECIALIST_SCIENTIST',		'YIELD_SCIENCE',				1),
		('POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE',	'SPECIALIST_WRITER',		'YIELD_GOLDEN_AGE_POINTS',		2),
		('POLICY_JFD_PHILOSOPHY_JALAL_RUMI',			'SPECIALIST_ARTIST',		'YIELD_FAITH',					1),
		('POLICY_JFD_PHILOSOPHY_JALAL_RUMI',			'SPECIALIST_MUSICIAN',		'YIELD_FAITH',					1),
		('POLICY_JFD_PHILOSOPHY_JALAL_RUMI',			'SPECIALIST_WRITER',		'YIELD_FAITH',					1),
		('POLICY_JFD_PHILOSOPHY_KARL_MARX',				'SPECIALIST_CITIZEN',		'YIELD_CULTURE',				1),
		('POLICY_JFD_PHILOSOPHY_KARL_MARX',				'SPECIALIST_CITIZEN',		'YIELD_TOURISM',				1),
		('POLICY_JFD_PHILOSOPHY_KARL_MARX',				'SPECIALIST_ENGINEER',		'YIELD_CULTURE',				1),
		('POLICY_JFD_PHILOSOPHY_KARL_MARX',				'SPECIALIST_ENGINEER',		'YIELD_TOURISM',				1),
		('POLICY_JFD_PHILOSOPHY_KARL_MARX',				'SPECIALIST_MERCHANT',		'YIELD_CULTURE',				1),
		('POLICY_JFD_PHILOSOPHY_KARL_MARX',				'SPECIALIST_MERCHANT',		'YIELD_TOURISM',				1),
		('POLICY_JFD_PHILOSOPHY_MAX_WEBER',				'SPECIALIST_MERCHANT',		'YIELD_SCIENCE',				1),
		('POLICY_JFD_PHILOSOPHY_MAX_WEBER',				'SPECIALIST_MERCHANT',		'YIELD_GOLD',					1),
		('POLICY_JFD_PHILOSOPHY_MAX_WEBER',				'SPECIALIST_SCIENTIST',		'YIELD_SCIENCE',				1),
		('POLICY_JFD_PHILOSOPHY_MAX_WEBER',				'SPECIALIST_SCIENTIST',		'YIELD_GOLD',					1),
		('POLICY_JFD_PHILOSOPHY_MOTOORI_NORINAGA',		'SPECIALIST_WRITER',		'YIELD_CULTURE',				1),
		('POLICY_JFD_PHILOSOPHY_MOTOORI_NORINAGA',		'SPECIALIST_WRITER',		'YIELD_FAITH',					1);

UPDATE Policy_SpecialistYieldChanges
SET SpecialistType = 'SPECIALIST_JFD_PERFORMER'
WHERE PolicyType = 'POLICY_JFD_PHILOSOPHY_JALAL_RUMI' AND SpecialistType = 'SPECIALIST_ARTIST'
AND EXISTS (SELECT Type FROM Specialists WHERE Type = 'SPECIALIST_JFD_PERFORMER');

INSERT INTO Policy_SpecialistYieldChanges
		(PolicyType,									SpecialistType,				YieldType,						Yield)
SELECT	'POLICY_JFD_PHILOSOPHY_FRIEDRICH_NIETZSCHE',	'SPECIALIST_JFD_DIRECTOR',	'YIELD_GOLDEN_AGE_POINTS',		2
WHERE EXISTS (SELECT Type FROM Specialists WHERE Type = 'SPECIALIST_JFD_DIRECTOR');
--------------------------------------------------------------------------------------------------------------------------
-- Policy_TourismOnUnitCreation
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_TourismOnUnitCreation
		(PolicyType,									UnitClassType,				Tourism)
VALUES	('POLICY_JFD_PHILOSOPHY_SWAMI_VIVEKANANDA',		'UNITCLASS_MISSIONARY',		20),
		('POLICY_JFD_PHILOSOPHY_SWAMI_VIVEKANANDA',		'UNITCLASS_PROPHET',		50);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_UnitClassProductionModifiers
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_UnitClassProductionModifiers
		(PolicyType,							UnitClassType,	ProductionModifier)
SELECT	'POLICY_JFD_PHILOSOPHY_JOHN_DEWEY',		Type,			20
FROM UnitClasses WHERE Type IN ('UNITCLASS_WORKER', 'UNITCLASS_JFD_WORKFORCE', 'UNITCLASS_SETTLER', 'UNITCLASS_CARAVAN', 'UNITCLASS_CARGO_SHIP', 'UNITCLASS_WORKBOAT', 'UNITCLASS_ARCHAEOLOGIST');

INSERT INTO Policy_UnitClassProductionModifiers
		(PolicyType,								UnitClassType,	ProductionModifier)
SELECT	'POLICY_JFD_PHILOSOPHY_JOHN_MEARSHEIMER',	Type,			15
FROM UnitClasses WHERE Type IN ('UNITCLASS_ATOMIC_BOMB', 'UNITCLASS_NUCLEAR_MISSILE');
--------------------------------------------------------------------------------------------------------------------------
-- Policy_YieldFromBirth
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_YieldFromBirth
		(PolicyType,									YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_JEAN_JACQUES_ROUSSEAU',	'YIELD_CULTURE',			50),
		('POLICY_JFD_PHILOSOPHY_MAIMONIDES',			'YIELD_GOLDEN_AGE_POINTS',	25);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_YieldFromNonSpecialistCitizens
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_YieldFromNonSpecialistCitizens
		(PolicyType,									YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_JOHN_MAYNARD_KEYNES',	'YIELD_GOLD',				4),
		('POLICY_JFD_PHILOSOPHY_JOHN_MAYNARD_KEYNES',	'YIELD_PRODUCTION',			4),
		('POLICY_JFD_PHILOSOPHY_JURGEN_HABERMAS',		'YIELD_SCIENCE',			3),
		('POLICY_JFD_PHILOSOPHY_WILL_KYMLICKA',			'YIELD_CULTURE',			4),
		('POLICY_JFD_PHILOSOPHY_WILL_KYMLICKA',			'YIELD_TOURISM',			4),
		('POLICY_JFD_PHILOSOPHY_XU_FUGUAN',				'YIELD_GOLDEN_AGE_POINTS',	1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_YieldChangesNaturalWonder
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_YieldChangesNaturalWonder
		(PolicyType,									YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_IMMANUEL_KANT',			'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_IMMANUEL_KANT',			'YIELD_GOLDEN_AGE_POINTS',	1),
		('POLICY_JFD_PHILOSOPHY_PYTHAGORAS',			'YIELD_FAITH',				2),
		('POLICY_JFD_PHILOSOPHY_THALES_OF_MILETUS',		'YIELD_SCIENCE',			2);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_YieldChangeTradeRoute
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_YieldChangeTradeRoute
		(PolicyType,									YieldType,			Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_GORGIAS',				'YIELD_GOLD',		2),
		('POLICY_JFD_PHILOSOPHY_VLADIMIR_DAL',			'YIELD_CULTURE',	2),
		('POLICY_JFD_PHILOSOPHY_VLADIMIR_DAL',			'YIELD_FAITH',		2),
		('POLICY_JFD_PHILOSOPHY_WANG_ANSHI',			'YIELD_FOOD',		1),
		('POLICY_JFD_PHILOSOPHY_WANG_ANSHI',			'YIELD_PRODUCTION',	1),
		('POLICY_JFD_PHILOSOPHY_ZHUANGZI',				'YIELD_CULTURE',	1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_YieldChangeWorldWonder
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_YieldChangeWorldWonder
		(PolicyType,									YieldType,					Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_IMMANUEL_KANT',			'YIELD_CULTURE',			1),
		('POLICY_JFD_PHILOSOPHY_IMMANUEL_KANT',			'YIELD_GOLDEN_AGE_POINTS',	1);
--------------------------------------------------------------------------------------------------------------------------
-- Policy_YieldModifierFromGreatWorks
--------------------------------------------------------------------------------------------------------------------------
INSERT INTO Policy_YieldModifierFromGreatWorks
		(PolicyType,									YieldType,			Yield)
VALUES	('POLICY_JFD_PHILOSOPHY_MICHEL_FOUCAULT',		'YIELD_CULTURE',	4);
--------------------------------------------------------------------------------------------------------------------------	
-- TRIGGERS
--------------------------------------------------------------------------------------------------------------------------
--JFD_GreatPhilosophers_Buildings
CREATE TRIGGER JFD_GreatPhilosophers_Buildings
AFTER INSERT ON Buildings
WHEN NEW.Cost = -1 AND NEW.FaithCost > 0 AND NEW.UnlockedByBelief = 1
BEGIN
	INSERT INTO Policy_BuildingClassYieldChanges
			(PolicyType,								BuildingClassType,	YieldType,			YieldChange)
	VALUES	('POLICY_JFD_PHILOSOPHY_MOHAMMAD_ABDUH',	NEW.BuildingClass,	'YIELD_FAITH',		2),
			('POLICY_JFD_PHILOSOPHY_MOHAMMAD_ABDUH',	NEW.BuildingClass,	'YIELD_SCIENCE',	2);
END;
--------------------------------------------------------------------------------------------------------------------------
--JFD_GreatPhilosophers_BuildingClasses1
CREATE TRIGGER JFD_GreatPhilosophers_BuildingClasses1
AFTER INSERT ON BuildingClasses
WHEN NEW.Type IN ('BUILDINGCLASS_EE_WEIGH_HOUSE')
BEGIN
	INSERT INTO Policy_BuildingClassProductionModifiers
			(PolicyType,							BuildingClassType,	ProductionModifier)
	SELECT	('POLICY_JFD_PHILOSOPHY_ADAM_SMITH',	NEW.Type,			20);
END;

--JFD_GreatPhilosophers_BuildingClasses2
UPDATE Policies
SET Help = 'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARNE_NAESS_HELP_WIND_FARM'
WHERE Type = 'POLICY_JFD_PHILOSOPHY_ARNE_NAESS'
AND EXISTS (SELECT Type FROM Buildings WHERE Type = 'BUILDING_JFD_WIND_FARM');	

CREATE TRIGGER JFD_GreatPhilosophers_BuildingClasses2
AFTER INSERT ON BuildingClasses
WHEN NEW.Type IN ('BUILDINGCLASS_JFD_WIND_FARM')
BEGIN
	UPDATE Policies
	SET Help = 'TXT_KEY_POLICY_JFD_PHILOSOPHY_ARNE_NAESS_HELP_WIND_FARM'
	WHERE Type = 'POLICY_JFD_PHILOSOPHY_ARNE_NAESS';	
END;

--JFD_GreatPhilosophers_BuildingClasses3
CREATE TRIGGER JFD_GreatPhilosophers_BuildingClasses3
AFTER INSERT ON BuildingClasses
WHEN NEW.MaxPlayerInstances = 1
BEGIN
	INSERT INTO Policy_BuildingClassYieldChanges
			(PolicyType,							BuildingClassType,	YieldType,					YieldChange)
	VALUES	('POLICY_JFD_PHILOSOPHY_JIANG_QING',	NEW.Type,			'YIELD_CULTURE',			2),
			('POLICY_JFD_PHILOSOPHY_JIANG_QING',	NEW.Type,			'YIELD_FAITH',				2),
			('POLICY_JFD_PHILOSOPHY_THOMAS_MORE',	NEW.Type,			'YIELD_GOLDEN_AGE_POINTS',	2);
			
	INSERT INTO Policy_BuildingClassProductionModifiers
			(PolicyType,							BuildingClassType,	 ProductionModifier)
	VALUES	('POLICY_JFD_PHILOSOPHY_MONTESQUIEU',	NEW.Type,			 15);
END;

--JFD_GreatPhilosophers_BuildingClasses4
CREATE TRIGGER JFD_GreatPhilosophers_BuildingClasses4
AFTER INSERT ON BuildingClasses
WHEN NEW.Type IN ('BUILDINGCLASS_EE_SALON')
BEGIN
	UPDATE Policies
	SET Help = 'TXT_KEY_POLICY_JFD_PHILOSOPHY_VOLTAIRE_HELP_SALON'
	WHERE PolicyType = 'POLICY_JFD_PHILOSOPHY_VOLTAIRE';
	
	UPDATE Policy_BuildingClassProductionModifiers
	SET BuildingClassType = 'BUILDINGCLASS_EE_SALON'
	WHERE PolicyType = 'POLICY_JFD_PHILOSOPHY_VOLTAIRE' AND BuildingClassType = 'BUILDINGCLASS_PUBLIC_SCHOOL';
	
	UPDATE Policy_BuildingClassYieldChanges
	SET BuildingClassType = 'BUILDINGCLASS_EE_SALON'
	WHERE PolicyType = 'POLICY_JFD_PHILOSOPHY_VOLTAIRE' AND BuildingClassType = 'BUILDINGCLASS_PUBLIC_SCHOOL';
END;

--JFD_GreatPhilosophers_BuildingClasses5
CREATE TRIGGER JFD_GreatPhilosophers_BuildingClasses5
AFTER INSERT ON BuildingClasses
WHEN NEW.Type IN ('BUILDINGCLASS_JFD_DIRECTORS_GUILD', 'BUILDINGCLASS_JFD_PERFORMERS_GUILD')
BEGIN
	INSERT INTO Policy_BuildingClassProductionModifiers
			(PolicyType,								BuildingClassType,	 ProductionModifier)
	VALUES	('POLICY_JFD_PHILOSOPHY_ZEAMI_MOTOKIYO',	NEW.Type,			 20);
END;
--------------------------------------------------------------------------------------------------------------------------
--JFD_GreatPhilosophers_Building_PrereqBuildingClasses
CREATE TRIGGER JFD_GreatPhilosophers_Building_PrereqBuildingClasses
AFTER INSERT ON Building_PrereqBuildingClasses
WHEN NEW.NumBuildingNeeded = -1
BEGIN
	INSERT INTO Policy_BuildingClassProductionModifiers
			(PolicyType,							BuildingClassType, 		 ProductionModifier)
	VALUES	('POLICY_JFD_PHILOSOPHY_MONTESQUIEU',	NEW.BuildingClassType,	 15);
END;
--------------------------------------------------------------------------------------------------------------------------
--JFD_GreatPhilosophers_GreatPersons
CREATE TRIGGER JFD_GreatPhilosophers_GreatPersons
AFTER INSERT ON GreatPersons
BEGIN
	INSERT INTO Policy_GreatPersonExpendedYield
			(PolicyType,									GreatPersonType, YieldType, 				 Yield)
	VALUES	('POLICY_JFD_PHILOSOPHY_PYRRHO',				NEW.Type,	 	 'YIELD_GOLDEN_AGE_POINTS',  50),
			('POLICY_JFD_PHILOSOPHY_RENE_DESCARTES',		NEW.Type,	 	 'YIELD_SCIENCE', 			 25),
			('POLICY_JFD_PHILOSOPHY_SOREN_KIERKEGAARD',		NEW.Type,	 	 'YIELD_FAITH', 			 100);
END;
--------------------------------------------------------------------------------------------------------------------------
--JFD_GreatPhilosophers_Improvements
CREATE TRIGGER JFD_GreatPhilosophers_Improvements
AFTER INSERT ON Improvements
WHEN NEW.CreatedByGreatPerson = 1
BEGIN
	INSERT INTO Policy_ImprovementYieldChanges
			(PolicyType,									ImprovementType, YieldType, 				Yield)
	VALUES	('POLICY_JFD_PHILOSOPHY_DAVID_HUME',			NEW.Type,	 	 'YIELD_CULTURE',			1),
			('POLICY_JFD_PHILOSOPHY_DAVID_HUME',			NEW.Type,	 	 'YIELD_GOLDEN_AGE_POINTS',	2),
			('POLICY_JFD_PHILOSOPHY_ST_AUGUSTINE',			NEW.Type,	 	 'YIELD_FAITH',				1),
			('POLICY_JFD_PHILOSOPHY_HENRY_ODERA_ORUKA',		NEW.Type,	 	 'YIELD_CULTURE',			2),
			('POLICY_JFD_PHILOSOPHY_HENRY_ODERA_ORUKA',		NEW.Type,	 	 'YIELD_TOURISM',			2);
END;
--------------------------------------------------------------------------------------------------------------------------
--JFD_GreatPhilosophers_Specialists
CREATE TRIGGER JFD_GreatPhilosophers_Specialists
AFTER INSERT ON Specialists
WHEN NEW.Type = 'SPECIALIST_JFD_PERFORMER'
BEGIN
	UPDATE Policy_SpecialistYieldChanges
	SET SpecialistType = 'SPECIALIST_JFD_PERFORMER'
	WHERE PolicyType = 'POLICY_JFD_PHILOSOPHY_JALAL_RUMI' AND SpecialistType = 'SPECIALIST_ARTIST';
END;
--------------------------------------------------------------------------------------------------------------------------	
--JFD_GreatPhilosophers_UnitClasses
CREATE TRIGGER JFD_GreatPhilosophers_UnitClasses
AFTER INSERT ON UnitClasses
WHEN NEW.Type IN ('UNITCLASS_JFD_WORKFORCE')
BEGIN
	INSERT INTO Policy_UnitClassProductionModifier
			(PolicyType,									UnitClassType,	ProductionModifier)
	VALUES	('POLICY_JFD_PHILOSOPHY_JOHN_DEWEY',			NEW.Type,		20);
END;
--==========================================================================================================================
--==========================================================================================================================