--==========================================================================================================================
-- TEXT
--==========================================================================================================================
-------------------------------------------------------------------------------------------------------------------------
-- Language_en_US
-------------------------------------------------------------------------------------------------------------------------
UPDATE Language_en_US
SET Text = REPLACE(Text, 'Autocracy', 'Fascism')
WHERE Tag IN ('TXT_KEY_POLICY_BRANCH_AUTOCRACY', 'TXT_KEY_WONDER_PRORA_RESORT_HELP', 'TXT_KEY_WONDER_STATUE_OF_LIBERTY_HELP', 'TXT_KEY_WONDER_KREMLIN_HELP', 'TXT_KEY_ADVISOR_CHOOSE_IDEOLOGY_BODY', 'TXT_KEY_SOCIALPOLICY_FREEDOM_HEADING3_BODY', 'TXT_KEY_CO_OPINION_TT_FOR_AUTOCRACY', 'TXT_KEY_CO_OPINION_TT_FOR_ORDER', 'TXT_KEY_CO_OPINION_TT_FOR_FREEDOM', 'TXT_KEY_GENERIC_SAME_POLICIES_AUTOCRACY_1', 'TXT_KEY_GENERIC_SAME_POLICIES_FREEDOM_1', 'TXT_KEY_GENERIC_SAME_POLICIES_ORDER_1', 'TXT_KEY_SOCIALPOLICY_IDEOLOGY_HEADING3_BODY', 'TXT_KEY_SOCIALPOLICY_AUTOCRACY_HEADING3_BODY', 'TXT_KEY_SOCIALPOLICY_ORDER_HEADING3_BODY');

UPDATE Language_en_US
SET Text = REPLACE(Text, 'Security', 'Fascism')
WHERE Tag IN ('TXT_KEY_POLICY_BRANCH_AUTOCRACY', 'TXT_KEY_WONDER_PRORA_RESORT_HELP', 'TXT_KEY_WONDER_STATUE_OF_LIBERTY_HELP', 'TXT_KEY_WONDER_KREMLIN_HELP', 'TXT_KEY_ADVISOR_CHOOSE_IDEOLOGY_BODY', 'TXT_KEY_SOCIALPOLICY_FREEDOM_HEADING3_BODY', 'TXT_KEY_CO_OPINION_TT_FOR_AUTOCRACY', 'TXT_KEY_CO_OPINION_TT_FOR_ORDER', 'TXT_KEY_CO_OPINION_TT_FOR_FREEDOM', 'TXT_KEY_GENERIC_SAME_POLICIES_AUTOCRACY_1', 'TXT_KEY_GENERIC_SAME_POLICIES_FREEDOM_1', 'TXT_KEY_GENERIC_SAME_POLICIES_ORDER_1', 'TXT_KEY_SOCIALPOLICY_IDEOLOGY_HEADING3_BODY', 'TXT_KEY_SOCIALPOLICY_AUTOCRACY_HEADING3_BODY', 'TXT_KEY_SOCIALPOLICY_ORDER_HEADING3_BODY');

UPDATE Language_en_US
SET Text = REPLACE(Text, 'Freedom', 'Liberalism')
WHERE Tag IN ('TXT_KEY_POLICY_BRANCH_FREEDOM', 'TXT_KEY_WONDER_PRORA_RESORT_HELP', 'TXT_KEY_WONDER_STATUE_OF_LIBERTY_HELP', 'TXT_KEY_WONDER_KREMLIN_HELP', 'TXT_KEY_ADVISOR_CHOOSE_IDEOLOGY_BODY', 'TXT_KEY_SOCIALPOLICY_FREEDOM_HEADING3_BODY', 'TXT_KEY_CO_OPINION_TT_FOR_AUTOCRACY', 'TXT_KEY_CO_OPINION_TT_FOR_ORDER', 'TXT_KEY_CO_OPINION_TT_FOR_FREEDOM', 'TXT_KEY_GENERIC_SAME_POLICIES_AUTOCRACY_1', 'TXT_KEY_GENERIC_SAME_POLICIES_FREEDOM_1', 'TXT_KEY_GENERIC_SAME_POLICIES_ORDER_1', 'TXT_KEY_SOCIALPOLICY_IDEOLOGY_HEADING3_BODY', 'TXT_KEY_SOCIALPOLICY_AUTOCRACY_HEADING3_BODY', 'TXT_KEY_SOCIALPOLICY_ORDER_HEADING3_BODY');

UPDATE Language_en_US
SET Text = REPLACE(Text, 'Order', 'Communism')
WHERE Tag IN ('TXT_KEY_POLICY_BRANCH_ORDER', 'TXT_KEY_WONDER_PRORA_RESORT_HELP', 'TXT_KEY_WONDER_STATUE_OF_LIBERTY_HELP', 'TXT_KEY_WONDER_KREMLIN_HELP', 'TXT_KEY_ADVISOR_CHOOSE_IDEOLOGY_BODY', 'TXT_KEY_SOCIALPOLICY_FREEDOM_HEADING3_BODY', 'TXT_KEY_CO_OPINION_TT_FOR_AUTOCRACY', 'TXT_KEY_CO_OPINION_TT_FOR_ORDER', 'TXT_KEY_CO_OPINION_TT_FOR_FREEDOM', 'TXT_KEY_GENERIC_SAME_POLICIES_AUTOCRACY_1', 'TXT_KEY_GENERIC_SAME_POLICIES_FREEDOM_1', 'TXT_KEY_GENERIC_SAME_POLICIES_ORDER_1', 'TXT_KEY_SOCIALPOLICY_IDEOLOGY_HEADING3_BODY', 'TXT_KEY_SOCIALPOLICY_AUTOCRACY_HEADING3_BODY', 'TXT_KEY_SOCIALPOLICY_ORDER_HEADING3_BODY', 'TXT_KEY_SOCIALPOLICY_AUTOCRACY_HEADING3_TITLE', 'TXT_KEY_SOCIALPOLICY_ORDER_HEADING3_TITLE', 'TXT_KEY_SOCIALPOLICY_FREEDOM_HEADING3_TITLE');

UPDATE Language_en_US
SET Text = REPLACE(Text, 'Spirit', 'Nationalism')
WHERE Tag LIKE '%TXT_KEY_POLICY_BRANCH_JFD_SPIRIT%';

UPDATE Language_en_US
SET Text = REPLACE(Text, 'Neutrality', 'Non-Alignment')
WHERE Tag LIKE '%TXT_KEY_POLICY_BRANCH_JFD_NEUTRALITY%';
--==========================================================================================================================
--==========================================================================================================================