INSERT INTO Unit_FreePromotions
		(UnitType, PromotionType)
SELECT	Type,	'PROMOTION_EW_SEIZERANGE'
FROM Units WHERE (CombatClass = 'UNITCOMBAT_SIEGE');

UPDATE Units
SET Range = 0
WHERE (CombatClass = 'UNITCOMBAT_SIEGE');

INSERT INTO UnitPromotions
		(Type,	Description,	Help,	PortraitIndex,	IconAtlas,	Sound,	RangeChange,	PediaType,	PediaEntry)
VALUES	('PROMOTION_EW_SEIZERANGE',	'TXT_KEY_PROMOTION_EW_SEIZERANGE',	'TXT_KEY_PROMOTION_EW_SEIZERANGE_HELP',	34,	'PROMOTION_ATLAS',	'AS2D_IF_LEVELUP',	2,	'PEDIA_RANGED',	'TXT_KEY_PROMOTION_EW_SEIZERANGE');