
INSERT INTO BuildingClasses
		(Type,														DefaultBuilding,										Description)
VALUES	('BUILDINGCLASS_MC_JERUSALEM_CHAPTER_HOUSE',				'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE',					'TXT_KEY_MC_CHAPTER_HOUSE'),
		('BUILDINGCLASS_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',		'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',			'TXT_KEY_MC_CHAPTER_HOUSE_TEMPLARS'),
		('BUILDINGCLASS_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',		'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',			'TXT_KEY_MC_CHAPTER_HOUSE_TEUTONIC'),
		('BUILDINGCLASS_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',			'TXT_KEY_MC_CHAPTER_HOUSE_ST_JOHN'),
		('BUILDINGCLASS_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',		'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',		'TXT_KEY_MC_CHAPTER_HOUSE_SEPULCHRE'),
		('BUILDINGCLASS_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',			'TXT_KEY_MC_CHAPTER_HOUSE_LAZARUS'),
		('BUILDINGCLASS_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',		'BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',		'TXT_KEY_MC_CHAPTER_HOUSE_CRUCIFORM'),
		-- Order Dummy Buildings
		('BUILDINGCLASS_MC_JERUSALEM_TEMPLARS',						'BUILDING_MC_JERUSALEM_TEMPLARS',						'TXT_KEY_MC_JERUSALEM_TEMPLARS_DUMMY'),
		('BUILDINGCLASS_MC_JERUSALEM_TEUTONIC',						'BUILDING_MC_JERUSALEM_TEUTONIC',						'TXT_KEY_MC_JERUSALEM_TEUTONIC_DUMMY'),
		('BUILDINGCLASS_MC_JERUSALEM_ST_JOHN',						'BUILDING_MC_JERUSALEM_ST_JOHN',						'TXT_KEY_MC_JERUSALEM_ST_JOHN_DUMMY'),
		('BUILDINGCLASS_MC_JERUSALEM_SEPULCHRE',					'BUILDING_MC_JERUSALEM_SEPULCHRE',						'TXT_KEY_MC_JERUSALEM_SEPULCHRE_DUMMY'),
		('BUILDINGCLASS_MC_JERUSALEM_LAZARUS',						'BUILDING_MC_JERUSALEM_LAZARUS',						'TXT_KEY_MC_JERUSALEM_LAZARUS_DUMMY'),
		('BUILDINGCLASS_MC_JERUSALEM_CRUCIFORM',					'BUILDING_MC_JERUSALEM_CRUCIFORM',						'TXT_KEY_MC_JERUSALEM_CRUCIFORM_DUMMY'),
		-- Chrisy's Dummies
		('BUILDINGCLASS_MC_JERUSALEM_LAZARUS_FAITH',				'BUILDING_MC_JERUSALEM_LAZARUS_FAITH',					'TXT_KEY_BUILDING_MC_JERUSALEM_LAZARUS_FAITH'),
		('BUILDINGCLASS_MC_JERUSALEM_TEMPLAR_FAITHGOLD',			'BUILDING_MC_JERUSALEM_TEMPLAR_FAITHGOLD',				'TXT_KEY_BUILDING_MC_JERUSALEM_TEMPLAR_FAITHGOLD'),
		('BUILDINGCLASS_MC_JERUSALEM_COOLDOWN_COUNTER',				'BUILDING_MC_JERUSALEM_COOLDOWN_COUNTER',				'TXT_KEY_BUILDING_MC_JERUSALEM_COOLDOWN_COUNTER');
		
INSERT INTO Buildings
		(Type,										BuildingClass,									Description,										Cost,		FaithCost,	GreatWorkCount,	PrereqTech,	NeverCapture,	NukeImmune,	IconAtlas,		PortraitIndex)
VALUES	('BUILDING_MC_JERUSALEM_LAZARUS_FAITH',		'BUILDINGCLASS_MC_JERUSALEM_LAZARUS_FAITH',		'TXT_KEY_BUILDING_MC_JERUSALEM_LAZARUS_FAITH',		-1,			-1,			-1,				NULL,		1,				1,			'BW_ATLAS_1',	13),
		('BUILDING_MC_JERUSALEM_TEMPLAR_FAITHGOLD',	'BUILDINGCLASS_MC_JERUSALEM_TEMPLAR_FAITHGOLD',	'TXT_KEY_BUILDING_MC_JERUSALEM_TEMPLAR_FAITHGOLD',	-1,			-1,			-1,				NULL,		1,				1,			'BW_ATLAS_1',	13),
		('BUILDING_MC_JERUSALEM_COOLDOWN_COUNTER',	'BUILDINGCLASS_MC_JERUSALEM_COOLDOWN_COUNTER',	'TXT_KEY_BUILDING_MC_JERUSALEM_COOLDOWN_COUNTER',	-1,			-1,			-1,				NULL,		1,				1,			'BW_ATLAS_1',	13);
		
INSERT INTO Building_ClassesNeededInCity
		(BuildingType,										BuildingClassType)
VALUES	('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE',				'BUILDINGCLASS_TEMPLE'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',	'BUILDINGCLASS_TEMPLE'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',	'BUILDINGCLASS_MC_JERUSALEM_TEMPLARS'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',	'BUILDINGCLASS_TEMPLE'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',	'BUILDINGCLASS_MC_JERUSALEM_TEUTONIC'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'BUILDINGCLASS_TEMPLE'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'BUILDINGCLASS_MC_JERUSALEM_ST_JOHN'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'BUILDINGCLASS_TEMPLE'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'BUILDINGCLASS_MC_JERUSALEM_SEPULCHRE'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'BUILDINGCLASS_TEMPLE'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'BUILDINGCLASS_MC_JERUSALEM_LAZARUS'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',	'BUILDINGCLASS_TEMPLE'),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',	'BUILDINGCLASS_MC_JERUSALEM_CRUCIFORM');
		
INSERT INTO Building_YieldChanges
		(BuildingType,										YieldType,			Yield)
VALUES	('BUILDING_MC_JERUSALEM_LAZARUS_FAITH',				'YIELD_FAITH',		2),
		('BUILDING_MC_JERUSALEM_TEMPLAR_FAITHGOLD',			'YIELD_FAITH',		1),
		('BUILDING_MC_JERUSALEM_TEMPLAR_FAITHGOLD',			'YIELD_GOLD',		3),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',	'YIELD_GOLD',		2),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',	'YIELD_PRODUCTION',	2),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'YIELD_SCIENCE',	2),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'YIELD_CULTURE',	2),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'YIELD_FOOD',		2),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',	'YIELD_FAITH',		2);

INSERT INTO Building_DomainFreeExperiences
		(BuildingType,										DomainType,		Experience)
VALUES	('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',	'DOMAIN_LAND',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',	'DOMAIN_SEA',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',	'DOMAIN_AIR',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',	'DOMAIN_LAND',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',	'DOMAIN_SEA',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',	'DOMAIN_AIR',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'DOMAIN_LAND',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'DOMAIN_SEA',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'DOMAIN_AIR',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'DOMAIN_LAND',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'DOMAIN_SEA',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'DOMAIN_AIR',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'DOMAIN_LAND',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'DOMAIN_SEA',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'DOMAIN_AIR',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',	'DOMAIN_LAND',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',	'DOMAIN_SEA',	10),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',	'DOMAIN_AIR',	10);

INSERT INTO Building_Flavors
		(BuildingType,										FlavorType,						Flavor)
VALUES	('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',	'FLAVOR_MILITARY_TRAINING',		20),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',	'FLAVOR_RELIGION',				15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEMPLARS',	'FLAVOR_GOLD',					15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',	'FLAVOR_MILITARY_TRAINING',		20),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',	'FLAVOR_RELIGION',				15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_TEUTONIC',	'FLAVOR_PRODUCTION',			15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'FLAVOR_MILITARY_TRAINING',		20),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'FLAVOR_RELIGION',				15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_ST_JOHN',		'FLAVOR_SCIENCE',				15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'FLAVOR_MILITARY_TRAINING',		20),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'FLAVOR_RELIGION',				15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_SEPULCHRE',	'FLAVOR_CULTURE',				15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'FLAVOR_MILITARY_TRAINING',		20),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'FLAVOR_RELIGION',				15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_LAZARUS',		'FLAVOR_GROWTH',				15),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',	'FLAVOR_MILITARY_TRAINING',		20),
		('BUILDING_MC_JERUSALEM_CHAPTER_HOUSE_CRUCIFORM',	'FLAVOR_RELIGION',				25);
		
INSERT INTO Civilization_BuildingClassOverrides
		(CivilizationType,	BuildingClassType,							BuildingType)
SELECT	Type,				'BUILDINGCLASS_MC_JERUSALEM_CHAPTER_HOUSE',	NULL
FROM Civilizations WHERE Type != 'CIVILIZATION_MC_JERUSALEM';

CREATE TRIGGER IF NOT EXISTS C15_Jerusalem_QuickFixUB -- Could've 2birds1stoned with the other trigger but rip
AFTER INSERT ON Civilizations
WHEN NEW.Type != 'CIVILIZATION_MC_JERUSALEM'
BEGIN
	INSERT INTO Civilization_BuildingClassOverrides
			(CivilizationType,	BuildingClassType,							BuildingType)
	VALUES	(NEW.Type,			'BUILDINGCLASS_MC_JERUSALEM_CHAPTER_HOUSE',	NULL);
END;