INSERT OR REPLACE INTO Buildings 	
			(Type, 						 					                     BuildingClass, 									      Description,		TechEnhancedTourism,		GreatWorkCount,		Cost,	FaithCost, PrereqTech, 	NeverCapture,	   NukeImmune,		           IconAtlas,	 PortraitIndex)
VALUES		('BUILDING_TOURISMHANDLER_0', 	 				  'BUILDINGCLASS_TOURISMHANDLER_0', 		    'TXT_KEY_SUKRITACT_TOURISM_DUMMY_0_OLMEC',		                  0,					-1,        -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_1', 	 				  'BUILDINGCLASS_TOURISMHANDLER_1', 		    'TXT_KEY_SUKRITACT_TOURISM_DUMMY_1_OLMEC',		                  1,					-1,        -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_2', 	 				  'BUILDINGCLASS_TOURISMHANDLER_2', 		    'TXT_KEY_SUKRITACT_TOURISM_DUMMY_2_OLMEC',		                  2,					-1,        -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_4', 	 				  'BUILDINGCLASS_TOURISMHANDLER_4', 		    'TXT_KEY_SUKRITACT_TOURISM_DUMMY_4_OLMEC',		                  4,					-1,        -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_8', 	 				  'BUILDINGCLASS_TOURISMHANDLER_8', 		    'TXT_KEY_SUKRITACT_TOURISM_DUMMY_8_OLMEC',		                  8,					-1,        -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_16', 	 				 'BUILDINGCLASS_TOURISMHANDLER_16', 		   'TXT_KEY_SUKRITACT_TOURISM_DUMMY_16_OLMEC',		                 16,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_32', 	 				 'BUILDINGCLASS_TOURISMHANDLER_32', 		   'TXT_KEY_SUKRITACT_TOURISM_DUMMY_32_OLMEC',		                 32,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_64', 	 				 'BUILDINGCLASS_TOURISMHANDLER_64', 		   'TXT_KEY_SUKRITACT_TOURISM_DUMMY_64_OLMEC',		                 64,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_128',  				'BUILDINGCLASS_TOURISMHANDLER_128', 	      'TXT_KEY_SUKRITACT_TOURISM_DUMMY_128_OLMEC',		                128,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_256',  				'BUILDINGCLASS_TOURISMHANDLER_256', 	      'TXT_KEY_SUKRITACT_TOURISM_DUMMY_256_OLMEC',		                256,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_512',  				'BUILDINGCLASS_TOURISMHANDLER_512', 	      'TXT_KEY_SUKRITACT_TOURISM_DUMMY_512_OLMEC',		                512,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_1024', 			   'BUILDINGCLASS_TOURISMHANDLER_1024',	         'TXT_KEY_SUKRITACT_TOURISM_DUMMY_1024_OLMEC',		               1024,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_2048', 			   'BUILDINGCLASS_TOURISMHANDLER_2048',	         'TXT_KEY_SUKRITACT_TOURISM_DUMMY_2048_OLMEC',		               2048,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_4096', 			   'BUILDINGCLASS_TOURISMHANDLER_4096',	         'TXT_KEY_SUKRITACT_TOURISM_DUMMY_4096_OLMEC',		               4096,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21),
			('BUILDING_TOURISMHANDLER_8192', 			   'BUILDINGCLASS_TOURISMHANDLER_8192',	         'TXT_KEY_SUKRITACT_TOURISM_DUMMY_8192_OLMEC',		               8192,					-1, 	   -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21);

INSERT OR REPLACE INTO BuildingClasses 	
			(Type, 						 		 		               DefaultBuilding, 						                    Description)
VALUES		('BUILDINGCLASS_TOURISMHANDLER_0', 			   'BUILDING_TOURISMHANDLER_0', 			  'TXT_KEY_SUKRITACT_TOURISM_DUMMY_0_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_1', 			   'BUILDING_TOURISMHANDLER_1', 			  'TXT_KEY_SUKRITACT_TOURISM_DUMMY_1_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_2', 			   'BUILDING_TOURISMHANDLER_2', 			  'TXT_KEY_SUKRITACT_TOURISM_DUMMY_2_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_4', 			   'BUILDING_TOURISMHANDLER_4', 			  'TXT_KEY_SUKRITACT_TOURISM_DUMMY_4_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_8', 			   'BUILDING_TOURISMHANDLER_8', 			  'TXT_KEY_SUKRITACT_TOURISM_DUMMY_8_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_16', 		  'BUILDING_TOURISMHANDLER_16', 			 'TXT_KEY_SUKRITACT_TOURISM_DUMMY_16_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_32', 		  'BUILDING_TOURISMHANDLER_32', 			 'TXT_KEY_SUKRITACT_TOURISM_DUMMY_32_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_64', 		  'BUILDING_TOURISMHANDLER_64', 			 'TXT_KEY_SUKRITACT_TOURISM_DUMMY_64_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_128', 		 'BUILDING_TOURISMHANDLER_128', 			'TXT_KEY_SUKRITACT_TOURISM_DUMMY_128_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_256', 		 'BUILDING_TOURISMHANDLER_256', 			'TXT_KEY_SUKRITACT_TOURISM_DUMMY_256_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_512', 		 'BUILDING_TOURISMHANDLER_512', 			'TXT_KEY_SUKRITACT_TOURISM_DUMMY_512_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_1024', 		'BUILDING_TOURISMHANDLER_1024', 		   'TXT_KEY_SUKRITACT_TOURISM_DUMMY_1024_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_2048', 		'BUILDING_TOURISMHANDLER_2048', 		   'TXT_KEY_SUKRITACT_TOURISM_DUMMY_2048_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_4096', 		'BUILDING_TOURISMHANDLER_4096', 		   'TXT_KEY_SUKRITACT_TOURISM_DUMMY_4096_OLMEC'),
			('BUILDINGCLASS_TOURISMHANDLER_8192', 		'BUILDING_TOURISMHANDLER_8192', 		   'TXT_KEY_SUKRITACT_TOURISM_DUMMY_8192_OLMEC');

INSERT OR REPLACE INTO Buildings 	
			(Type, 						 					                      BuildingClass, 									       Description,		 TechEnhancedTourism,		GreatWorkCount,		Cost,	FaithCost, PrereqTech, 	NeverCapture,	   NukeImmune,		           IconAtlas,	 PortraitIndex)
VALUES		('BUILDING_TOURISMHANDLER_40', 	 				  'BUILDINGCLASS_TOURISMHANDLER_40', 		    'TXT_KEY_SUKRITACT_TOURISM_DUMMY_40_OLMEC',		                  40,					-1,        -1,         -1, 		 NULL,			   1,				1,				'BW_ATLAS_1',				21);

INSERT OR REPLACE INTO BuildingClasses 	
			(Type, 						 		 		                    DefaultBuilding, 						                     Description)
VALUES		('BUILDINGCLASS_TOURISMHANDLER_40', 			   'BUILDING_TOURISMHANDLER_40', 			  'TXT_KEY_SUKRITACT_TOURISM_DUMMY_40_OLMEC');